<div class="w">
    <div class="breadcrumb">
        <strong><a href="/">首页</a></strong>
        <span>&nbsp;&gt;&nbsp;<a href="/">关于家大</a>&nbsp;&gt;&nbsp;<a href="">企业简介</a></span>
    </div>
</div>
<div class="w main">
    <div class="left">
        <div class="news_category">
            <div class="mt">
                <h2>
                    关于家大
                </h2>
            </div>
            <div class="mc">
                <ul class="conact_side">
                    <li><a href="http://www.jd.com/intro/about.aspx">企业简介</a></li>
                    <li><a href="http://www.jd.com/intro/team.aspx">企业创始人</a></li>
                    <li><a href="http://www.jd.com/intro/culture.aspx">企业文化</a></li>
                    <li><a href="http://www.jd.com/intro/memorabilia.aspx">大 事 记</a></li>
                    <li><a href="http://www.jd.com/intro/honor.aspx">企业荣誉</a></li>
                    <li><a href="http://www.jd.com/intro/service.aspx">广告服务</a></li>
                    <li><a href="http://zhaopin.jd.com/">人才招聘</a></li>
                    <li><a href="http://help.en.jd.com/help/question-31.html">About us</a></li>
                    <li><a href="http://ir.jd.com" target="_blank">Investor Relations</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="right-extra">
        <div class="content">
            <h1 class="tit">关于家大（jiada.biz）</h1>
            <h3>公司介绍：</h3>
            <p>“家大”社区超市由北京家大信息技术有限公司创办，经过长达一年时间的准备，终于开始营业了。家大社区超市为小区居民提供在线购物、电话购物、免费配送、货到付款、7天无理由退换货、15-45分钟急速送货上门等服务。我们的口语是“在您身边！”。
                我们的目标是“做世界上最好的超市、最好的服务，将大型超市搬到您的家里，让您足不出户就能享受安全、快速、轻松、愉快的购物”。我们志存高远，追求“商品质量第一！物流配送第一！服务水准第一！”的远大目标，以“诚信、安全、健康、服务”为本，
                在供应商筛选、商品质量检测、商品入库和入驻商家引进以及日常运营监管等环节上，由专业人员严格把关，保障高质量的服务标准。我们严格遵守国家有关“三包”的法律法规，让顾客放心购买。 1000平米立体式仓库，近50人的优秀团队，家大社区超市将为您
                提供全新的生活方式和生活理念，我们坚持不懈为您打造优质生活，竭诚为民服务。 
            </p>
            <h3>我们的优势：</h3>
            <p>

 一、便捷的购物方式 区别于传统购物方式，我们提供了“网上下单”和“电话下单”两种订货方式；送货上门、货到付款、7天无理由退换货服务，竭诚的努力只为将超市搬至到您的家门口。
</p>
            <p>
 二、快速的物流配送，我们不但能在15-45分钟将所购商品送到您的家中，还能在您上班之前或下班之后根据您的要求将商品按时送到您的家中，您不用再担心家里无人、和快递人员协商甚至吵闹第二天才能收到货物。
</p>
            <p>
 三、客服热线答疑，企业的真正价值，源于对消费者无微不至的关心，我们的客服做到了这一点。您的认同才是我们不断前进的动力！
</p>
            <p>
四、质量价格体系，我们不打价格战，所售商品价格均不高于市场价格。我们以“人”为本，不卖假货，由专业人员严格把关，保障商品和服务的高质量，并严格遵照国家相关法律法规，让顾客放心购买！
            </p>
            <h3>配送服务说明：</h3>

            <p>极速达：“极速达”配送服务是为您提供的一项个性化付费增值服务，如您选择“极速达”配送服务，需通过“在线支付”方式全额成功付款或“货到付款”方式成功提交订单后，并选中“极速达”服务后，我们会在服务时间内，15-45分钟将商品送至您家中。</p>
            <p>早上免费配送：当日下单后第二天早上05:30 - 07:30送达。0元起送，免费配送。（为上班族定制）</p>
            <p>晚上免费配送：当日19:00之前下单后，当日晚上19:00 - 21:00送达。0元起送，免费配送。（为上班族定制）</p>

	  </div>
    </div>
    <div class="clr"> </div>
</div>