<div class="w w0">
    <div class="m m1">
        <div class="cates"></div>
    </div>
    <div class="m m2">
        <div id="flash1" class="slideBox">
            <ul class="items">
                <li><a href="go/to/your/url.html" title="这里是测试标题一"><img src="http://gtms01.alicdn.com/tps/i1/T1zYA4Fk4fXXb1upjX.jpg"></a></li>
                <li><a href="go/to/your/url.html" title="这里是测试标题二"><img src="http://gtms01.alicdn.com/tps/i1/T1spA0FbRuXXcmO1ke-950-350.jpg"></a></li>
                <li><a href="go/to/your/url.html" title="这里是测试标题三"><img src="http://gtms01.alicdn.com/tps/i1/T16ZpoFB4cXXcmO1ke-950-350.jpg"></a></li>

            </ul>
        </div>
        <!--综合区活动展示-->
        <div class="all_variety_acts">
            <a href="http://www.tmall.com/"><img src="http://gtms02.alicdn.com/tps/i2/T1XS8KFs0vXXXYsa3B-188-147.jpg"></a><a href="http://www.tmall.com/"><img src="http://gtms02.alicdn.com/tps/i2/T1HM0PFzXXXXXYsa3B-188-147.jpg"></a><a href="http://www.tmall.com/"><img src="http://gtms03.alicdn.com/tps/i3/T1EIdLFB0dXXXYsa3B-188-147.jpg"></a><a href="http://www.tmall.com/"><img src="http://gtms03.alicdn.com/tps/i3/T1wTXOFv8aXXXYsa3B-188-147.jpg"></a>
        </div>
    </div>
    <div class="m m3">
        <div class="mod_news" id="index_news">
            <p class="tabs">
                <a href="javascript:void(0);" data-tbcontentid="1" class="marketRight_mod_news_tab tb1 cur">家大公告</a>
                <a href="javascript:void(0);" data-tbcontentid="2" class="marketRight_mod_news_tab tb2">家大新闻</a>
            </p>
            <div class="content" id="marketRight_mod_news_tab_content_1" style="display: block;">
                <ul class="news_list">
                    <li><a data-ref="1812_9288729_1" href="http://cms.yhd.com/cmsPage/show.do?pageId=65066&amp;ref=ad.1812_9288729_1" title="2月11日部分订单取消的公告" target="_blank">
                            2月11日部分订单取消的
                        </a></li>
                    <li><a data-ref="1812_8974786_2" href="http://cms.yhd.com/cmsPage/show.do?pageId=64430&amp;ref=ad.1812_8974786_2" title="订单延误公告" target="_blank">
                            订单延误公告
                        </a></li>
                    <li><a data-ref="1812_9045155_3" href="http://cms.yhd.com/cmsPage/show.do?pageId=63684&amp;ref=ad.1812_9045155_3" title="杜蕾斯免费领德芙超值优惠" target="_blank">
                            杜蕾斯免费领德芙超值优惠
                        </a></li>
                    <li><a data-ref="1812_9331742_4" href="http://cms.yhd.com/cmsPage/show.do?pageId=64092&amp;ref=ad.1812_9331742_4" title="元宵全场满送烧麦小点" target="_blank">
                            元宵全场满送烧麦小点
                        </a></li>
                    <li><a data-ref="1812_6677561_5" href="http://www.yhd.com/hotq/?ref=ad.1812_6677561_5" title=" 家大用户搜索热词上线" target="_blank">
                            家大用户搜索热词上线
                        </a></li>
                </ul>
            </div>
            <div class="content" id="marketRight_mod_news_tab_content_2" style="display: none;">
                <ul class="news_list">
                    <li><a data-ref="3_7552471_1" href="http://cms.yhd.com/cms/view.do?topicId=24268&amp;cache=false&amp;ref=ad.3_7552471_1" title="去年家大销售额破百亿" target="_blank">
                            去年家大销售额破百亿
                        </a></li>
                    <li><a data-ref="3_7552473_2" href="http://cms.yhd.com/cms/view.do?topicId=24266&amp;cache=false&amp;ref=ad.3_7552473_2" title="家大开出首张电子发票 " target="_blank">
                            家大开出首张电子发票
                        </a></li>
                    <li><a data-ref="3_7552474_3" href="http://cms.yhd.com/cms/view.do?topicId=24267&amp;cache=false&amp;ref=ad.3_7552474_3" title="家大设立水产直供基地" target="_blank">
                            家大设立水产直供基地
                        </a></li>
                    <li><a data-ref="3_7552476_4" href="http://cms.yhd.com/cms/view.do?topicId=24264&amp;cache=false&amp;ref=ad.3_7552476_4" title="家大深耕进口食品市场" target="_blank">
                            家大深耕进口食品市场
                        </a></li>
                    <li><a data-ref="3_7552478_5" href="http://cms.yhd.com/cms/view.do?topicId=24265&amp;cache=false&amp;ref=ad.3_7552478_5" title="抢吃千亿进口食品市场 " target="_blank">
                            抢吃千亿进口食品市场
                        </a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="clr"></div>
<div class="w w1" >
    <?php
                        
        if(isset($floor) && $floor && is_array($floor)){
            foreach ($floor as $key => $f) {
    ?>
    <div class="floor" data-floor="<?php echo $key;?>">
        <div class="m m1">
            <div class="mt">
                <h2><?php echo $f['floorName'];?></h2>
            </div>
            <div class="mc">
                <div class="catalogue">
                    <ul>
                        <?php
                            //商品类型
                            if (isset($f['floorData']['goodsType']) && $f['floorData']['goodsType']) {
                                foreach ($f['floorData']['goodsType'] as $item) {
                                    $nodes=$item['parentPath'].','.$item['cateId'];
                            ?>
                                    <li><a href="<?php echo "/List?cat={$nodes}";?>" target="_blank"><?php echo $item['cateName']; ?></a></li>
                            <?php
                                }
                            }
                        ?>
                        <?php
                            //品牌
                            if (isset($f['floorData']['catesBrand']) && $f['floorData']['catesBrand']) {
                                foreach ($f['floorData']['catesBrand'] as $item) {
                            ?>
                                    <li><a href="javascript:void();" ><?php echo $item['brandName']; ?></a></li>
                            <?php
                                }
                            }
                        ?>
                    </ul>
                    <span class="ad">
			<a target="_blank" title="" href="javascript:void();">
                            <img width="209" height="155" alt="家居馆" src="http://img12.360buyimg.com/da/g1/M04/00/04/rBEGD1NwLrMIAAAAAABNox2pR4EAABaOwLDEigAAE27922.jpg" class="err-product">
                        </a>
                    </span>
                </div>
            </div>

        </div>
        <div class="m m2">
            <div class="tab-arrow" style="left: 0px;"><b></b></div>
            <div class="mt">
                <ul class="index_nav">
                        <?php
                        if (isset($f['floorData']['catesGoods']) && $f['floorData']['catesGoods']) {
                            foreach ($f['floorData']['catesGoods'] as $k => $item) {
                                if ($k == 0) {
                                    $curr_class = ' hover';
                                } else {
                                    $curr_class = '';
                                }
                                ?>
                                <li><a class="<?php echo $curr_class; ?>" href="javascript:void(0);" data-id="<?php echo $k;?>"><?php echo $item['name']; ?></a></li>
                                <?php
                            }
                        }
                        ?>
                </ul>
            </div>
            <div class="mc">
                <?php
                if (isset($f['floorData']['catesGoods']) && $f['floorData']['catesGoods']) {
                    foreach ($f['floorData']['catesGoods'] as $k=>$items) {
                        if($k==0){
                            $curr_display=' block;';
                        }  else {
                            $curr_display=' none;';
                        }
                ?>
                <div class="plist" id="nav_content_<?php echo $key; ?>_<?php echo $k;?>" style="display:<?php echo $curr_display;?>;">
                    <ul>
                        <?php
                            $catesGoods=@$items['data'];
                            if(isset($catesGoods) && $catesGoods){
                                foreach ($catesGoods as $item) {
                                    if(isset($item['packPic']) && $item['packPic']){
                                        $pics=explode(',', $item['packPic']);
                                        $firstPic=$pics[0];
                                        $goodsPic=$fileImg_obj->generateImgUrl(array('imgSize'=>'160X160','imgUrl'=>$firstPic), $imagesConfig);
                                    }else{
                                        $goodsPic='';
                                    }
                        ?>
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="<?php echo '/detail?p='.$item['priceId'];?>" title="<?php echo $item['goodsName'];?>">
                                    <img src="<?php echo $goodsPic;?>" height="160" width="160" alt="<?php echo $item['goodsName'];?>">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="<?php echo '/detail?p='.$item['priceId'];?>" title="<?php echo $item['goodsName'];?>">
                                    <?php echo $item['goodsName'];?>
                                </a>
                            </div>
                            <div class="p-price"><del>¥<?php echo $item['originalPrice'];?></del><span>¥<?php echo $item['currentPrice'];?></span></div>
                            
                        </li>
                        <?php
                            }
                        }
                        ?>
                    </ul>
                </div>
                <?php
                    }
                }
                ?>
                <div class="plist" id="nav_content_1_1" style="display: none;">
                    <ul>
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price"><del>¥499.80</del><span>¥499.80</span></div>
                            
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clr"></div>
    </div>
    <?php
            }
        }
    ?>
    <div class="floor" data-floor="2">
        <div class="m m1">
            <div class="mt">
                <h2>牛奶乳品</h2>
            </div>
            <div class="mc">
                <div class="catalogue">
                    <ul>
                        <li><a href="http://channel.jd.com/furniture.html">家具</a></li>
                        <li><a href="http://www.360buy.com/products/1620-1623-000.html">灯具照明</a></li>
                        <li><a href="http://www.360buy.com/products/1620-1625-000.html">家用清洁</a></li>
                        <li><a href="http://www.360buy.com/products/1620-1624-000.html">居家日用</a></li>
                        <li><a href="http://www.360buy.com/products/6196-6219-000.html">水具/酒具</a></li>
                        <li><a href="http://www.360buy.com/products/6196-6197-000.html">烹饪锅具</a></li>
                        <li><a href="http://channel.jd.com/6196-6214.html">厨房配件</a></li>
                        <li><a href="http://www.360buy.com/products/6196-6227-000.html">餐具</a></li>
                        <li><a href="http://list.jd.com/1620-1621-1626.html">床品套件</a></li>
                        <li><a href="http://list.jd.com/1620-1621-1632-0-0-0-0-0-0-0-1-1-1-1-1-72-4137-0.html">蚊帐</a></li>
                        <li><a href="http://list.jd.com/1620-1621-1627-0-0-0-0-0-0-0-1-1-1-1-1-72-4137-0.html">夏被</a></li>
                        <li><a href="http://list.jd.com/1620-1621-11963-0-0-0-0-0-0-0-1-1-1-1-1-72-4137-0.html">凉席</a></li>
                        <li><a href="http://channel.jd.com/decoration.html">家装建材</a></li>
                        <li><a href="http://channel.jd.com/pet.html">宠物生活</a></li>
                        <li><a href="http://channel.jd.com/9192-9196.html">成人用品</a></li>
                        <li><a href="http://list.jd.com/1620-1625-1671-0-0-0-0-0-0-0-1-1-1-1-1-72-4137-0.html">生活用纸</a></li>
                    </ul>
                    <span class="ad">
			<a target="_blank" title="" href="#">
                            <img width="209" height="155" alt="家居馆" src="http://img12.360buyimg.com/da/g1/M04/00/04/rBEGD1NwLrMIAAAAAABNox2pR4EAABaOwLDEigAAE27922.jpg" class="err-product">
                        </a>
                    </span>
                </div>
            </div>

        </div>
        <div class="m m2">
            <div class="tab-arrow" style="left: 0px;"><b></b></div>
            <div class="mt">
                <ul class="index_nav">
                    <li><a class="hover" href="javascript:void(0);" data-id="0">纯牛奶</a></li>
                    <li><a href="javascript:void(0);" data-id="1">酸奶</a></li>
                    <li><a href="javascript:void(0);" data-id="2">儿童奶</a></li>
                </ul>
            </div>
            <div class="mc">
                <div class="plist" id="nav_content_2_0">
                    <ul>
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price"><del>¥499.80</del><span>¥499.80</span></div>
                            
                        </li>
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price">¥<span>499.80</span></div>
                            
                        </li>
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price">¥<span>499.80</span></div>
                            
                        </li>
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price">¥<span>499.80</span></div>
                            
                        </li>
                        <li class="lastItem">
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price">¥<span>499.80</span></div>
                            
                        </li>
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price">¥<span>499.80</span></div>
                            
                        </li>
                    </ul>
                </div>
                <div class="plist" id="nav_content_2_1" style="display: none;">
                    <ul>
                        
                        <li>
                            <div class="p-img ld">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    <img src="http://www.taobz.com/upload/store/goods/3/3_587dce3980d6bdc19701fe98cb576ab1.jpg_small.jpg" height="160" width="160" alt="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                </a>
                            </div>
                            <div class="p-name">
                                <a target="_blank" href="http://item.jd.com/1093776931.html" title="爆款限时抢 罗莱LOVO全棉高支斜纹四件套">
                                    爆款限时抢 罗莱LOVO全棉高支斜纹四件套
                                </a>
                            </div>
                            <div class="p-price">¥<span>499.80</span></div>
                            
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clr"></div>
    </div>
</div>