<!--sidebar-menu-->
<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
  <ul>
    <li class="active"><a href="#"><i class="icon icon-home"></i> <span>起始页</span></a> </li>
    
    <li class="submenu open"> <a href="#"><i class="icon icon-th-list"></i> <span>商品管理</span> <span class="label label-important">3</span></a>
      <ul>
        <li><a href="/admin/goodscate/index">商品分类</a></li>
        <li><a href="/admin/goodscate/add">添加商品分类</a></li>
        <li><a href="/admin/goodscate/index">商品品牌</a></li>
        <li><a href="/admin/goodscate/add">添加商品品牌</a></li>
        <li class="active" ><a href="#">商品列表</a></li>
        <li><a href="#">添加新商品</a></li>
      </ul>
    </li>
    <li class="submenu"> <a href="#"><i class="icon icon-th-list"></i> <span>交易管理</span> <span class="label label-important">2</span></a>
      <ul>
        <li><a href="#">订单管理</a></li>
        <li><a href="gallery.html">用户评论</a></li>
      </ul>
    </li>
    <li class="submenu"> <a href="#"><i class="icon icon-th-list"></i> <span>区域管理</span> <span class="label label-important">2</span></a>
      <ul>
        <li><a href="/admin/area/index">地区列表</a></li>
        <li><a href="/admin/area/add">新增地区</a></li>
      </ul>
    </li>
    <li><a href="buttons.html"><i class="icon icon-fullscreen"></i> <span>促销管理</span></a></li>
    <li><a href="interface.html"><i class="icon icon-th"></i> <span>广告管理</span></a></li>
    <li><a href="buttons.html"><i class="icon icon-th"></i> <span>会员管理</span></a></li>
    <li><a href="buttons.html"><i class="icon icon-pencil"></i> <span>权限管理</span></a></li>
    
    <li><a href="interface.html"><i class="icon icon-th"></i> <span>报表统计</span></a></li>
    
    <li class="submenu"> <a href="#"><i class="icon icon-info-sign"></i> <span>Error</span> <span class="label label-important">4</span></a>
      <ul>
        <li><a href="error403.html">Error 403</a></li>
        <li><a href="error404.html">Error 404</a></li>
        <li><a href="error405.html">Error 405</a></li>
        <li><a href="error500.html">Error 500</a></li>
      </ul>
    </li>
    
<!--    <li class="content"> <span>Monthly Bandwidth Transfer</span>
      <div class="progress progress-mini progress-danger active progress-striped">
        <div style="width: 77%;" class="bar"></div>
      </div>
      <span class="percent">77%</span>
      <div class="stat">21419.94 / 14000 MB</div>
    </li>
    <li class="content"> <span>Disk Space Usage</span>
      <div class="progress progress-mini active progress-striped">
        <div style="width: 87%;" class="bar"></div>
      </div>
      <span class="percent">87%</span>
      <div class="stat">604.44 / 4000 MB</div>
    </li>-->
    
  </ul>
</div>
<!--sidebar-menu-->