
<!--breadcrumbs-->
<div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="/Admin/Goodsbrand/index/cateId/<?php echo $gcateInfo['cateId'];?>" class="tip-bottom">商品品牌</a> <a href="#" class="current">添加</a> </div>
    <h1>商品品牌管理</h1>
</div>

<!--End-breadcrumbs-->
<div class="container-fluid">
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Goods Brand-info</h5>
                </div>
                <div class="widget-content nopadding">
                    <form action="" method="post" class="form-horizontal">
                        <div class="control-group">
                            <label class="control-label">分类 :</label>
                            <div class="controls">
                                
                                <input type="text" name="cateName"  value="<?php echo $gcateInfo['cateName'];?>" class="span5" readonly/>
                                <input type="hidden" name="cateId" <?php echo $this->_view->getInputAttrs($rules, 'cateId') ?> id="cateId" value="<?php if(isset($post['cateId'])){ echo $post['cateId'];}else{echo $gcateInfo['cateId'];}?>" class="span5"  />
                                <div class="col-md-8 col-md-offset-3 showmsg">
                                    <?php
                                    if (isset($error['cateId'])) {
                                        $this->_view->showValidateError($error['cateId']);
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">商品类型 :</label>
                            <div class="controls">
                                <?php
                                    foreach($childCateType as $key=>$v){
                                ?>
                                <span><input type="checkbox" name="childCateType[]" <?php echo $this->_view->getInputAttrs($rules, 'childCateType') ?> value="<?php echo $v['cateId'];?>" <?php if(in_array($v['cateId'], $post['childCateType'])) echo ' checked';?>/> <?php echo $v['cateName'];?></span>
                                <?php
                                    }
                                ?>
                               <div class="col-md-8 col-md-offset-3 showmsg">
                                    <?php
                                    if (isset($error['childCateType'])) {
                                        $this->_view->showValidateError($error['childCateType']);
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">商品品牌名称 :</label>
                            <div class="controls">
                                <input type="text" name="brandName" <?php echo $this->_view->getInputAttrs($rules, 'brandName') ?> id="brandName" value="<?php if(isset($post['brandName'])) echo $post['brandName']?>" class="span5" placeholder="三元 蒙牛 伊利" />
                                <div class="col-md-8 col-md-offset-3 showmsg">
                                    <?php
                                    if (isset($error['brandName'])) {
                                        $this->_view->showValidateError($error['brandName']);
                                    }
                                    ?>
                                </div>
                            </div>
                            
                        </div>
                        <div class="control-group">
                            <label class="control-label">拼音 :</label>
                            <div class="controls">
                                <input type="text" name="pinyin" <?php echo $this->_view->getInputAttrs($rules, 'pinyin') ?> id="pinyin" value="<?php if(isset($post['brandName'])) echo $post['pinyin']?>" class="span5" placeholder="sanyuan mengniu yili" />
                                <div class="col-md-8 col-md-offset-3 showmsg">
                                    <?php
                                    if (isset($error['pinyin'])) {
                                        $this->_view->showValidateError($error['pinyin']);
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">是否公开 :</label>
                            <div class="controls">
                                <label>
                                    <input type="radio" name="status" value="1" checked <?php if(isset($post['status'])){ if($post['status']==1){echo ' checked';}else{ echo ' ';}}?>/>
                                    是
                                </label>
                                <label>
                                    <input type="radio" name="status" value="0" <?php if(isset($post['status'])){ if($post['status']==0){echo ' checked';}else{ echo ' ';}}?>/>
                                    否 
                                </label>
                            </div>
                        </div>
                        


                        <div class="form-actions">
                            <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                            <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
                        </div>
                    </form>
                </div>
            </div>


        </div>

    </div>

</div>
