<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">商品品牌管理</a> </li>
    <li class="active">列表</li>
</ul>

<div class="widget-list">

    <div class="widget-event">
        <span class="submenu pull-right"><button type="submit" name="jsubmit" value="del" class="btn btn-sm btn-info" >删除</button></span>
        <span class="submenu pull-right"><button type="submit" name="jsubmit" value="add" class="btn btn-sm btn-info" onclick="location.href = '/Admin/Goodsbrand/add/cateId/<?php echo $cateId; ?>';">添加品牌</button></span>
    </div>
    <div class="widget-content">
        <form name="jform" id="jform" action="" method="post" class="form-horizontal">
            <div class="search">
                <span class="col-sm-2 nopadding">
                    <select name="status" class="form-control input-sm">
                        <option value="all" <?php if (isset($post['status']) && $post['status'] == '') {
                            echo ' selected';
                        } else {
                            echo '';
                        } ?>>显示所有</option>
                        <option value="1" <?php if (isset($post['status']) && $post['status'] == 1) {
                            echo ' selected';
                        } else {
                            echo '';
                        } ?>>已公开</option>
                    </select>
                </span>

                <span>
                    <button type="submit" name="jsubmit" value="search" class="btn btn-default btn-sm" >检索</button>
                </span>

            </div>


            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                        <th>品牌名称</th>
                        <th>拼音</th>
                        <th>所属分类</th>
                        <th>商品类型</th>
                        <th>状态</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (is_array($data) && !empty($data)) {
                        foreach ($data as $key => $item) {
                            ?>
                           <tr>
                                <td class="checkids"><input type="checkbox" name="checkIds[]" value="<?php echo $item['brandId']; ?>"/></td>
                                <td><a href="/admin/goodsbrand/edit/brandId/<?php echo $item['brandId']; ?>"><?php echo $item['brandName']; ?></a></td>
                                <td><?php echo $item['pinyin']; ?></td>
                                <td><?php echo $item['cateName']; ?></td>
                                <td><?php echo $item['childCateType']; ?></td>
                                <td><?php if ($item['status'] == 1) {
                                                echo '已公开';
                                            } else {
                                                echo '未公开';
                                            } ?>
                                </td>
                            </tr>
                                <?php
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="6">无数据！</td>
                            </tr>
                            <?php
                        }
                        ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6"><?php echo $pagination; ?></td>
                    </tr>

                </tfoot>
            </table>
        </form>
    </div>

</div>
