<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=gbk" />
        <title>J-framework</title>
        <link href="<?php echo $this->baseurl;?>/templates/system/css/main.css" rel="stylesheet" type="text/css" />
<!--
        <script language="javascript">
            function switchSysBar(){
                if (parent.document.getElementById('_main_').cols=="188,*"){

                    parent.document.getElementById('_main_').cols="0,*";
                }
                else{
                    parent.document.getElementById('_main_').cols="188,*";
                }
            }

        </script>
-->
    </head>

    <body>
        <div id="top">
            <div id="logo"></div>
            <div id="user">欢迎您:admin  IP:192.168.0.124</div>	 
        </div>
        <!--<span  onclick="switchSysBar()">打开/关闭左栏</span>-->
    </body>
</html>
