<style type="text/css">
    body{margin:0px;padding:0px;font-family:Arial;}
    a img,:link img,:visited img { border: none; }
    table { border-collapse: collapse; border-spacing: 0; }
    :focus { outline: none; }
    *{margin:0;padding:0;}
    /*            p, blockquote, dd, dt{margin:0 0 8px 0;line-height:1.5em;}*/
    fieldset {padding:0px;padding-left:7px;padding-right:7px;padding-bottom:7px;}
    fieldset legend{margin-left:15px;padding-left:3px;padding-right:3px;color:#333;}
    dl dd{margin:0px;}
    dl dt{}

    .clearfix:after{clear:both;content:".";display:block;font-size:0;height:0;line-height:0;visibility:hidden;}
    .clearfix{display:block;zoom:1}


    ul#thumblist{display:block;}
    ul#thumblist li{float:left;margin-right:2px;list-style:none;}
    ul#thumblist li a{display:block;border:1px solid #CCC;}
    ul#thumblist li a.zoomThumbActive{
        border:1px solid red;
    }

    .jqzoom{

        text-decoration:none;
        float:left;
    }

</style>
<div class="w">
    <div class="breadcrumb">
        <?php
        if (isset($cateNodes['nodePath']) && $cateNodes['nodePath']) {
            foreach ($cateNodes['nodePath'] as $key => $cateId) {
                if (isset($cateNodes['nodeItems'][$cateId]['cateName'])) {
                    if ($key == 0) {
                        echo '<strong><a href="#">' . $cateNodes['nodeItems'][$cateId]['cateName'] . '</a></strong>';
                        echo '<span>&nbsp;&gt;&nbsp;';
                    } else {
                        echo '<a href="#">' . $cateNodes['nodeItems'][$cateId]['cateName'] . '</a>&nbsp;&gt;&nbsp;';
                    }
                    if (count($cateNodes['nodePath']) == $key + 1) {
                        echo '</span>';
                    }
                }
            }
        }
        ?>

    </div>
</div>
<div class="w">
    <div id="product-intro" class="">
        <?php
        if (isset($goodsInfo['packPic']) && $goodsInfo['packPic']) {
            $goodsPics = explode(',', $goodsInfo['packPic']);
            $firstPic = $goodsPics[0];
//                            $firstSmallPic = $fileImg_obj->generateImgUrl(array('imgSize' => '60X60', 'imgUrl' => $firstPic), $imagesConfig);
            $firstMediumPic = $fileImg_obj->generateImgUrl(array('imgSize' => '360X360', 'imgUrl' => $firstPic), $imagesConfig);
            $firstLargePic = $fileImg_obj->generateImgUrl(array('imgSize' => '800X800', 'imgUrl' => $firstPic), $imagesConfig);
        } else {
            $firstMediumPic = '';
            $firstLargePic = '';
            $goodsPic = '';
        }
        ?>
        <div id="preview">
            <div class="clearfix" id="content" style="margin-top:0px;margin-left:0px; height:360px;width:360px;" >
                <div class="clearfix">
                    <a href="<?php echo $firstLargePic; ?>" class="jqzoom" rel='gal1'  title="<?php echo $goodsInfo['goodsName']; ?>" >
                        <img src="<?php echo $firstMediumPic; ?>"  title="triumph"  style="" width="360" height="360">
                    </a>
                </div>
                <br/>
                <div class="clearfix" >
                    <ul id="thumblist" class="clearfix" >
                        <?php
                        if (isset($goodsPics) && $goodsPics) {
                            foreach ($goodsPics as $k => $pic) {
                                $smallPic = $fileImg_obj->generateImgUrl(array('imgSize' => '60X60', 'imgUrl' => $pic), $imagesConfig);
                                $mediumPic = $fileImg_obj->generateImgUrl(array('imgSize' => '360X360', 'imgUrl' => $pic), $imagesConfig);
                                $largePic = $fileImg_obj->generateImgUrl(array('imgSize' => '800X800', 'imgUrl' => $pic), $imagesConfig);
                                if ($k == 0) {
                                    $activeClass = ' class="zoomThumbActive"';
                                } else {
                                    $activeClass = '';
                                }
                                ?>
                                <li><a <?php echo $activeClass; ?> href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '<?php echo $mediumPic; ?>',largeimage: '<?php echo $largePic; ?>'}"><img src='<?php echo $smallPic; ?>' width="60" height="60"></a></li>
                                <?php
                            }
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
        <div id="info">
            <div class="product_name"><h1><?php echo $goodsInfo['goodsName']; ?></h1></div>
            <div class="clearfix" clstag="">
                <ul id="summary">
                    <?php
                    if (isset($goodsInfo['marketPrice']) && $goodsInfo['marketPrice'] > 0) {
                        ?>
                        <li id="summary-market">
                            <div class="dt">参&nbsp;考&nbsp;价：</div>
                            <div class="dd"><del id="page_maprice">￥<?php echo $goodsInfo['marketPrice']; ?></del></div>
                        </li>
                        <?php
                    }
                    ?>
                    <li id="summary-price">
                        <div class="dt">家&nbsp;大&nbsp;价：</div>
                        <div class="dd">
                            <strong class="p-price" id="jd-price">￥<?php echo $goodsInfo['currentPrice']; ?></strong>
                        </div>
                    </li>
                    <li id="summary-service" >
                        <div class="dt">服　　务：</div>
                        <div class="dd">
                            由<a href="#" target="_blank" clstag="shangpin|keycount|product|bbtn" class="hl_red">家大超市</a>负责发货，并提供售后服务。
                        </div>
                    </li>
                    <li id="choose-btns">

                    </li>
                </ul>

                <!--summary end-->
            </div>
            <div class="sku_unit  buy_act" id="computingAndBtnArea">
                <div class="computing" id="computingArea">
                    <div class="computerbox clearfix">
                        <div class="computing_item" data-sel="num" id="computing_item">
                            <div class="computing_num">
                                <input type="text" value="1" class="num" data-max="999" data-min="1" id="product_amount">
                            </div>
                            <div class="computing_act">
                                <input type="button" class="add" value="+" id="add">
                                <input type="button" class="reduce" value="-" id="reduce">
                            </div>
                        </div>
                        <div class="cartbox" id="BtnArea">
                            <span class="form-btn group common-button">
                                <a href="javascript:void(0);" class="buybutton button" id="buyThis" shopid="<?php echo $goodsInfo['shopId']; ?>" product="<?php echo $priceId; ?>">
                                    <span>加入购物车</span>
                                </a>
                                <div class="loading loading-2" style="display:none"><b></b>正在提交信息，请等待！</div>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="w">
    <div class="left">
        <div id="related-sorts" class="m m2" clstag="shangpin|keycount|product|sortlist">
            <div class="mt">
                <h2>相关分类</h2>
            </div>
            <div class="mc">
                <ul class="lh">					
                    <li><a href="http://list.jd.com/1320-1583-1590.html" title="休闲零食">休闲零食</a></li><li><a href="http://list.jd.com/1320-1583-1591.html" title="坚果炒货">坚果炒货</a></li><li><a href="http://list.jd.com/1320-1583-1592.html" title="肉干肉松">肉干肉松</a></li><li><a href="http://list.jd.com/1320-1583-1593.html" title="蜜饯果脯">蜜饯果脯</a></li><li><a href="http://list.jd.com/1320-1583-1594.html" title="糖果/巧克力">糖果/巧克力</a></li><li><a href="http://list.jd.com/1320-1583-1595.html" title="饼干蛋糕">饼干蛋糕</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="right">
        <div class="product-detail">
            <div class="pnav">
                <ul id="pnav_tabs">
                    <li><a href="#" name="#pnav_tab1">商品介绍</a></li>
                    <li><a href="#" name="#pnav_tab2">规格参数</a></li>
                    <li><a href="#" name="#pnav_tab3">包装清单</a></li>
                    <li><a href="#" name="#pnav_tab4">商品评价(999)</a></li>    
                </ul>


            </div>
            <div id="pnav_content">
                <div id="pnav_tab1">
                    <?php echo $goodsDetail['goodsDesc']; ?>
                </div>
                <div id="pnav_tab2">
                    <h2>Vivamus fringilla suscipit justo</h2>
                    <p>Aenean dui nulla, egestas sit amet auctor vitae, facilisis id odio. Donec dictum gravida feugiat.</p>
                    <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras pretium elit et erat condimentum et volutpat lorem vehicula</p>

                    <p>Morbi tincidunt pharetra orci commodo molestie. Praesent ut leo nec dolor tempor eleifend.</p>    
                </div>
                <div id="pnav_tab3">
                    <h2>Phasellus non nibh</h2>
                    <p>Non erat laoreet ullamcorper. Pellentesque magna metus, feugiat eu elementum sit amet, cursus sed diam. Curabitur posuere porttitor lorem, eu malesuada tortor faucibus sed.</p>
                    <h3>Duis pulvinar nibh vel urna</h3>
                    <p>Donec purus leo, porttitor eu molestie quis, porttitor sit amet ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec accumsan ornare elit id imperdiet. </p>
                    <p>Suspendisse ac libero mauris. Cras lacinia porttitor urna, vitae molestie libero posuere et. </p>
                </div>
                <div id="pnav_tab4">
                    <h2>Cum sociis natoque penatibus</h2>
                    <p>Magnis dis parturient montes, nascetur ridiculus mus. Nullam ac massa quis nisi porta mollis venenatis sit amet urna. Ut in mauris velit, sed bibendum turpis.</p>
                    <p>Nam ornare vulputate risus, id volutpat elit porttitor non. In consequat nisi vel lectus dapibus sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent bibendum sagittis libero.</p>
                    <h3>Imperdiet sem interdum nec</h3>
                    <p>Mauris rhoncus tincidunt libero quis fringilla.</p>    
                </div>
            </div>
        </div>

    </div>
</div>