<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>"  title="Go to Home">主页</a> </li>
    <li class="active">面板</li>
</ul>

<div class="widget-list">

    <div class="widget-content">
        <form name="jform" id="jform" action="" method="post" class="form-horizontal">
            
        </form>
    </div>

</div>