<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="<?php echo "/$_ModuleName/Shop/index/shopId/$currentShopId" ?>"  title="Go to Home">主页</a> </li>
    <li class="active">商品发布</li>
</ul>

<div class="widget-list">

    <div class="widget-content">
        <form name="jform" id="jform" action="" method="post" class="form-horizontal">
            <div class="search">
                <!--这是一个通用的无限级联动菜单，主要参数：id data-next data-url；-->
                <div id="search_content" class="row" style="padding-left: 15px;">
                    <span class="col-sm-2 nopadding">
                        <select name="cateId" id="nodeCate1" class="form-control input-sm linkage" data-next="#nodeCate2" data-url="/Chaoshi/Goods/nodeGcate/cateId">
                            <option value="" selected>--选择分类--</option>
                            <?php
                            if(isset($nodeCate1)){
                                foreach ($nodeCate1 as $cate) {
                                    if (in_array($cate['id'], $post_select_cateId)) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $cate['id'] . '" ' . $selected . '>' . $cate['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </span>
                    <span class="col-sm-2 nopadding">
                        <select name="cateId" id="nodeCate2" class="form-control input-sm linkage" data-next="#nodeCate3" data-url="/Chaoshi/Goods/nodeGcate/cateId" <?php if(isset($nodeCate2)){echo ' style="display: block;"';}else{echo ' style="display: none;"';}?>>
                            <option value="" selected>--选择分类--</option>
                            <?php
                            if(isset($nodeCate2)){
                                foreach ($nodeCate2 as $cate) {
                                    if (in_array($cate['id'], $post_select_cateId)) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $cate['id'] . '" ' . $selected . '>' . $cate['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </span>
                    <span class="col-sm-2 nopadding">
                        <select name="cateId" id="nodeCate3" class="form-control input-sm linkage" data-next="#catebrands" data-url="/Chaoshi/Goods/gcatebrand/cateId"  <?php if(isset($nodeCate3)){echo ' style="display: block;"';}else{echo ' style="display: none;"';}?>>
                            <option value="" selected>--选择分类--</option>
                            <?php
                            if(isset($nodeCate3)){
                                foreach ($nodeCate3 as $cate) {
                                    if (in_array($cate['id'], $post_select_cateId)) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $cate['id'] . '" ' . $selected . '>' . $cate['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </span>
                    <span class="col-sm-2 nopadding">
                        <select name="brandId" id="catebrands" class="form-control input-sm linkage" data-next="" data-url=""  <?php if(isset($catebrands)){echo ' style="display: block;"';}else{echo ' style="display: none;"';}?>>
                            <option value="" selected>--选择品牌--</option>
                            <?php
                            if(isset($catebrands)){
                                foreach ($catebrands as $brand) {
                                    if ($brand['id']==$post['brandId']) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $brand['id'] . '" ' . $selected . '>' . $brand['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </span>
                </div>
                <br />
                <span>
                <input type="text" name="goodsName" value="<?php if (isset($post['goodsName'])) {echo $post['goodsName'];} ?>" class="input-sm form-control input3" placeholder="商品关键词：有机奶"/>
                </span>
                <span>
                    <button type="submit" name="jsubmit" value="search" class="btn btn-default btn-sm" >检索</button>
                </span>
                

            </div>


            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>商品名称</th>
                        <th>商品分类</th>
                        <th>商品品牌</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ( isset($data) && !empty($data) && is_array($data)) {
                        foreach ($data as $key => $item) {
                            ?>
                            <tr>
                                <td><a href="javascript:void(0);"><?php echo $item['goodsName']; ?></a></td>
                                <td><?php echo $item['cateName']; ?></td>
                                <td><?php echo $item['brandName']; ?></td>
                                <td><?php if($item['priceId']){echo '已发布';}else{ echo '未发布';}?></td>
                                <td>
                                    <?php if($item['priceId']){
                                    ?>
                                    【<a href="<?php echo "/$_ModuleName/Shopgoods/edit/shopId/$shopId/goodsId/$item[goodsId]";?>">查看商品</a>】
                                    <?php
                                    }else{
                                    ?>
                                    【<a href="<?php echo "/$_ModuleName/$_ControllerName/price/shopId/$shopId/goodsId/$item[goodsId]";?>">发布商品</a>】
                                    <?php
                                    }
                                    ?>
                                    
                                </td>
                            </tr>
                            <?php
                        }
                    } else {
                        ?>
                        <tr>
                            <td colspan="8" class="red">请根据分类或商品名称搜索商品！</td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="8"><?php echo $pagination; ?></td>
                    </tr>

                </tfoot>
            </table>
        </form>
    </div>

</div>