<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index/shopId/$currentShopId"; ?>">商品管理</a> </li>
    <li class="active">添加库存</li>
</ul>
<!--End-breadcrumbs-->
<div class="widget-box">
    <form action="" method="post" class="form-horizontal validate">
        <div class="form-group control-group">
            <label class="col-sm-2 control-label">商品分类 :</label>
            <div class="col-sm-10">
                <p class="form-control-static">
                    <?php
                    if (isset($goodsInfo['cateName'])) {
                        echo $goodsInfo['cateName'];
                    }
                    ?>
                </p>

            </div>
        </div>
        <div class="form-group control-group">
            <label class="col-sm-2 control-label">商品品牌 :</label>
            <div class="col-sm-10">
                <p class="form-control-static">
                    <?php
                    if (isset($goodsInfo['brandName'])) {
                        echo $goodsInfo['brandName'];
                    }
                    ?>
                </p>
            </div>
        </div>

        <div class="form-group control-group">
            <label class="col-sm-2 control-label">商品名称 :</label>
            <div class="col-sm-10">
                <p class="form-control-static">
                    <?php
                    if (isset($goodsInfo['goodsName'])) {
                        echo $goodsInfo['goodsName'];
                    }
                    ?>
                </p>
            </div>

        </div>

        <div class="form-group control-group">
            <label class="col-sm-2 control-label"> <b class="bold red">*</b> 进货数量 :</label>
            <div class="col-sm-10">
                <input type="text" name="quantity" <?php echo $this->_view->getInputAttrs($rules, 'quantity') ?> id="quantity" value="<?php
                if (isset($post['quantity'])) {
                    echo $post['quantity'];
                }
                ?>" class="form-control" placeholder="进货数量" />
                <div class="showmsg">
                    <?php
                    if (isset($error['quantity'])) {
                        $this->_view->showValidateError($error['quantity']);
                    }
                    ?>
                </div>
            </div>                            
        </div>
        <div class="form-group control-group">
            <label class="col-sm-2 control-label"><b class="bold red">*</b>进货价格 :</label>
            <div class="col-sm-10">
                <input type="text" name="purchasePrice" <?php echo $this->_view->getInputAttrs($rules, 'purchasePrice') ?> id="marketPrice" value="<?php
                if (isset($post['purchasePrice'])) {
                    echo $post['purchasePrice'];
                }
                ?>" class="form-control" placeholder="进货价格" />
                <div class="showmsg">
                    <?php
                    if (isset($error['purchasePrice'])) {
                        $this->_view->showValidateError($error['purchasePrice']);
                    }
                    ?>
                </div>
            </div>                            
        </div>

        <div class="form-group control-group">
            <label class="col-sm-2 control-label"><b class="bold red">*</b>进货时间 :</label>
            <div class="col-md-10">
                <input type="text" name="putinTime" id="putinTime"  value="<?php
                if (isset($post['putinTime'])) {
                    echo $post['putinTime'];
                }
                ?>" class="datepicker input-sm form-control input2" placeholder="到货时间" />
            </div>                          
        </div>



        <div class="form-actions">
            <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
            <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
        </div>

    </form>
</div>

<script src="//<?php echo $_config_domain['static']; ?>/plugin/datetimepicker/js/jquery.datetimepicker.js"></script>
<script>
    $('#putinTime').datetimepicker({
        lang: 'ch',
        format: 'Y-m-d H:i',
        step: 1
    });
</script>