
<!--breadcrumbs-->
<div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#" class="tip-bottom">商品属性分类</a> <a href="#" class="current">添加</a> </div>
    <h1>商品属性分类管理</h1>
</div>

<!--End-breadcrumbs-->
<div class="container-fluid">
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="/admin/goodsattrcate/index/cateId/<?php echo $goodsCateId;?>">商品属性分类管理</a></li>
                        <li><a href="/admin/goodsattr/index/cateId/<?php echo $goodsCateId;?>">商品属性管理</a></li>
                    </ul>
                </div>
                <div class="widget-content nopadding tab-content">
                    <div id="tab1" class="tab-pane active">
                        <form action="/admin/goodsattrcate/add/cateId/<?php echo $goodsCateId;?>" name="jform" id="jform" method="post" class="form-horizontal">
                            <div class="control-group">
                                <label class="control-label">商品分类 :</label>
                                <div class="controls">
                                    <input type="text" name="cateName" id="cateName" value="<?php echo $gcateInfo['cateName'] ?>" class="span5"  readonly />
                                    <input type="hidden" name="goodsCateId" <?php echo $this->_view->getInputAttrs($rules, 'goodsCateId') ?> id="cateId" value="<?php echo $gcateInfo['cateId'] ?>" class="span5"   readonly/>
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['goodsCateId'])) {
                                            $this->_view->showValidateError($error['goodsCateId']);
                                        }
                                        ?>
                                    </div>
                                </div>

                            </div>
                            <div class="control-group">
                                <label class="control-label">商品属性分类名称 :</label>
                                <div class="controls">
                                    <input type="text" name="attrCateName" <?php echo $this->_view->getInputAttrs($rules, 'attrCateName') ?> id="attrCateName" value="" class="span5" placeholder="基本属性" />
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['attrCateName'])) {
                                            $this->_view->showValidateError($error['attrCateName']);
                                        }
                                        ?>
                                    </div>
                                </div>

                            </div>
                            <div class="control-group">
                                <label class="control-label">排序 :</label>
                                <div class="controls">
                                    <input type="text" name="sort" <?php echo $this->_view->getInputAttrs($rules, 'sort') ?> id="sort" value="" class="span5" placeholder="0 1 2 3" />
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['sort'])) {
                                            $this->_view->showValidateError($error['sort']);
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success" onclick="ajaxForm('jform');
                                        return false;">Save</button>
                                <button type="reset" class="btn btn-primary">Reset</button>
                            </div>
                        </form>
                    </div>
                    <div id="tab2" class="tab-pane">
                        
                    </div>

                </div>
            </div>



        </div>

    </div>

</div>
