
<!--breadcrumbs-->
<div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#" class="tip-bottom">商品属性分类</a> <a href="#" class="current">列表</a> </div>
    <h1>商品属性分类管理</h1>
</div>

<!--End-breadcrumbs-->
<div class="container-fluid">
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="/admin/goodsattrcate/index/cateId/<?php echo $goodsCateId;?>">商品属性分类管理</a></li>
                        <li><a href="/admin/goodsattr/index/cateId/<?php echo $goodsCateId;?>">商品属性管理</a></li>
                    </ul>
                </div>
                <div class="widget-content nopadding tab-content">
                    <div id="tab1" class="tab-pane active">
                        <p style="display: block;padding-top: 3px;margin-right: 5px;float: right;">
                            <button type="submit" name="jsubmit" value="add" class="btn" onclick="ajaxForm('jform', '/Admin/Goodsattrcate/del/cateId/<?php echo $goodsCateId;?>');return false;">删除</button> <button type="submit" name="jsubmit" value="add" class="btn" onclick="location = '/admin/goodsattrcate/add/cateId/<?php echo $goodsCateId; ?>'">添加属性分类</button>
                        </p> 
                        

                        <form action="" name="jform" id="jform" method="post" class="form-horizontal">
                            <table class="table table-bordered table-striped with-check">
                                <thead>
                                    <tr>
                                        <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                                        <th>商品类型</th>
                                        <th>商品分类</th>
                                        <th>排序</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    if (is_array($data) && !empty($data)) {
                                        foreach ($data as $key => $item) {
                                            ?>
                                            <tr>
                                                <td><input type="checkbox" name="checkIds[]" value="<?php echo $item['attrCateId']; ?>"/></td>
                                                <td><a href="/admin/goodsattrcate/edit/attrCateId/<?php echo $item['attrCateId']; ?>"><?php echo $item['attrCateName']; ?></a></td>
                                                <td><?php echo $gcateInfo['cateName']; ?></td>
                                                <td><?php echo $item['sort']; ?></td>
                                            </tr>
                                            <?php
                                        }
                                    } else {
                                        ?>
                                        <tr>
                                            <td colspan="6">无数据！</td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="6"><?php echo $pagination; ?></td>
                                    </tr>

                                </tfoot>
                            </table>
                        </form>
                        <p></p>
                    </div>
                    <div id="tab2" class="tab-pane">

                    </div>

                </div>
            </div>



        </div>

    </div>

</div>
