<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">用户组管理</a> </li>
    <li class="active">列表</li>
</ul>
<div class="widget-list">
    <form name="jform" id="jform" action="" method="post" class="form-horizontal">

        <div class="widget-content">
            <div class="search">
                <span class="col-sm-2 nopadding">
                    <select name="status" class="form-control input-sm">
                        
                        <option value="1" <?php
                        if (isset($post['status']) && $post['status'] == 1) {
                            echo ' selected';
                        } else {
                            echo ' selected';
                        }
                        ?>>正常</option>
                        <option value="-1" <?php
                        if ($post['status'] == -1) {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>已禁用</option>
                    </select>
                </span>

                <span>
                    <button type="submit" name="jsubmit" value="search" class="btn btn-default btn-sm" >检索</button>
                </span>
            </div>

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                        <th>用户组名称</th>
                        <th>继承父类权限</th>
                        <th>状态</th>
                    </tr>
                </thead>
                <tbody>
                        <?php
                        if (is_array($data) && !empty($data)) {
                            foreach ($data as $key => $item) {
                        ?>
                            <tr>
                                <td class="checkids"><input type="checkbox" name="checkIds[]" value="<?php echo $item['agroupId']; ?>"/></td>
                                <td><a href="<?php echo "/$_ModuleName/$_ControllerName/edit/agroupId/$item[agroupId]"; ?>"><?php echo $item['groupName']; ?></a></td>
                                <td>
                                    <?php
                                    if ($item['extends'] == 1) {
                                        echo '是';
                                    } else {
                                        echo '否';
                                    }
                                ?>
                                    
                                </td>
                                <td>
                                <?php
                                    if ($item['status'] == 1) {
                                        echo '正常';
                                    } else {
                                        echo '已禁用';
                                    }
                                ?>
                                </td>
                            </tr>
                            <?php
                                }
                            } else {
                            ?>
                        <tr>
                            <td colspan="5">无数据！</td>
                        </tr>
                    <?php
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5"><?php echo $pagination; ?></td>
                    </tr>

                </tfoot>
            </table>
        </div>
    </form>
</div>
</div>