<div class="content">
    <div class="mod_order_head">
        <font class="tit">我的订单</font>
        <div class="recpt_bor"></div>
    </div>
    <div class="mod_order_list">
        <div class="order">
            <div class="order_left">
                <p class="order_link">
                    <a href="javascript:void(0);" class="icon_order" target="_blank">包裹1</a>
                    <font>来自</font>
                    <a href="javascript:void(0);" target="_blank" >家大自营</a>

                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                </p>
                <p class="order_screen_list">
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d3.yihaodianimg.com/t1/2012/01/12/4138133_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N00/M00/50/31/CgQCtlF3n8SARtFyAAN-tTp_AGs29501_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N03/M05/3A/56/CgQCs1FVLQGACX_bAAHVbLMB-iM84001_60x60.jpg">
                    </a>
                </p>
                <hr size="1">
                <p class="order_link">
                    <a href="javascript:void(0);" class="icon_order" target="_blank">包裹2</a>
                    <font>来自</font>
                    <a href="javascript:void(0);" target="_blank" >家大自营</a>

                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                </p>
                <p class="order_screen_list">
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d3.yihaodianimg.com/t1/2012/01/12/4138133_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N00/M00/50/31/CgQCtlF3n8SARtFyAAN-tTp_AGs29501_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N03/M05/3A/56/CgQCs1FVLQGACX_bAAHVbLMB-iM84001_60x60.jpg">
                    </a>
                </p>
                <div class="clr"></div>
            </div>
            <div class="order_right">

                <ul>
                    <li class="ordering_time">
                        <span class="year">2013</span>
                        <span class="month">09/11</span><br>
                    </li>
                    <li class="order_num">
                        订单号：130911CHJP5C
                    </li>
                    <li class="order_amount">
                        <span class="price_sen">¥</span>
                        <span class="price">89.</span>
                        <span class="price_sen">90</span>
                    </li>
                    <li class="order_operating">
                        <a href="javascript:void(0);" class="default_btn">再次购买</a>
                        <a href="javascript:void(0);" class="default_btn blue" target="_blank">查看订单</a>

                    </li>
                </ul>
            </div>
            <div class="clr"></div>
        </div>
        <div class="order">
            <div class="order_left">
                <p class="order_link">
                    <a href="javascript:void(0);" class="icon_order" target="_blank">包裹1</a>
                    <font>来自</font>
                    <a href="javascript:void(0);" target="_blank" >家大自营</a>

                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                </p>
                <p class="order_screen_list">
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d3.yihaodianimg.com/t1/2012/01/12/4138133_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N00/M00/50/31/CgQCtlF3n8SARtFyAAN-tTp_AGs29501_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N03/M05/3A/56/CgQCs1FVLQGACX_bAAHVbLMB-iM84001_60x60.jpg">
                    </a>
                </p>
                <hr size="1">
                <p class="order_link">
                    <a href="javascript:void(0);" class="icon_order" target="_blank">包裹2</a>
                    <font>来自</font>
                    <a href="javascript:void(0);" target="_blank" >家大自营</a>

                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                </p>
                <p class="order_screen_list">
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d3.yihaodianimg.com/t1/2012/01/12/4138133_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N00/M00/50/31/CgQCtlF3n8SARtFyAAN-tTp_AGs29501_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N03/M05/3A/56/CgQCs1FVLQGACX_bAAHVbLMB-iM84001_60x60.jpg">
                    </a>
                </p>
                <div class="clr"></div>
            </div>
            <div class="order_right">

                <ul>
                    <li class="ordering_time">
                        <span class="year">2013</span>
                        <span class="month">09/11</span><br>
                    </li>
                    <li class="order_num">
                        订单号：130911CHJP5C
                    </li>
                    <li class="order_amount">
                        <span class="price_sen">¥</span>
                        <span class="price">89.</span>
                        <span class="price_sen">90</span>
                    </li>
                    <li class="order_operating">
                        <a href="javascript:void(0);" class="default_btn">再次购买</a>
                        <a href="javascript:void(0);" class="default_btn blue" target="_blank">查看订单</a>

                    </li>
                </ul>
            </div>
            <div class="clr"></div>
        </div>
        <div class="order">
            <div class="order_left">
                <p class="order_link">
                    <a href="javascript:void(0);" class="icon_order" target="_blank">包裹1</a>
                    <font>来自</font>
                    <a href="javascript:void(0);" target="_blank" >家大自营</a>

                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                </p>
                <p class="order_screen_list">
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d3.yihaodianimg.com/t1/2012/01/12/4138133_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N00/M00/50/31/CgQCtlF3n8SARtFyAAN-tTp_AGs29501_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N03/M05/3A/56/CgQCs1FVLQGACX_bAAHVbLMB-iM84001_60x60.jpg">
                    </a>
                </p>
                <hr size="1">
                <p class="order_link">
                    <a href="javascript:void(0);" class="icon_order" target="_blank">包裹2</a>
                    <font>来自</font>
                    <a href="javascript:void(0);" target="_blank" >家大自营</a>

                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                </p>
                <p class="order_screen_list">
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d3.yihaodianimg.com/t1/2012/01/12/4138133_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N00/M00/50/31/CgQCtlF3n8SARtFyAAN-tTp_AGs29501_60x60.jpg">
                    </a>
                    <a class="pa" href="" target="_blank" >
                        <img src="http://d6.yihaodianimg.com/N03/M05/3A/56/CgQCs1FVLQGACX_bAAHVbLMB-iM84001_60x60.jpg">
                    </a>
                </p>
                <div class="clr"></div>
            </div>
            <div class="order_right">

                <ul>
                    <li class="ordering_time">
                        <span class="year">2013</span>
                        <span class="month">09/11</span><br>
                    </li>
                    <li class="order_num">
                        订单号：130911CHJP5C
                    </li>
                    <li class="order_amount">
                        <span class="price_sen">¥</span>
                        <span class="price">89.</span>
                        <span class="price_sen">90</span>
                    </li>
                    <li class="order_operating">
                        <a href="javascript:void(0);" class="default_btn">再次购买</a>
                        <a href="javascript:void(0);" class="default_btn blue" target="_blank">查看订单</a>

                    </li>
                </ul>
            </div>
            <div class="clr"></div>
        </div>
        <div class="clr"></div>
    </div>
</div>