<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">管理员管理</a> </li>
    <li class="active">列表</li>
</ul>
<div class="widget-list">
    <form name="jform" id="jform" action="" method="post" class="form-horizontal">

        <div class="widget-content">
            <div class="search">
                <span class="col-sm-2 nopadding">
                    <select name="agroupId" id="agroupId" class="form-control">
                        <option value="0" selected>顶级</option>
                        <?php echo $treeAgroup; ?>
                    </select>
                </span>

                <span>
                    <button type="submit" name="jsubmit" value="search" class="btn btn-default btn-sm" >检索</button>
                </span>
            </div>

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                        <th>真实姓名</th>
                        <th>登录名</th>
                        <th>所属组</th>
                        <th>状态</th>
                    </tr>
                </thead>
                <tbody>
                        <?php
                        if (is_array($data) && !empty($data)) {
                            foreach ($data as $key => $item) {
                        ?>
                            <tr>
                                <td class="checkids"><input type="checkbox" name="checkIds[]" value="<?php echo $item['adminId']; ?>"/></td>
                                <td><a href="/Admin/Admin/edit/adminId/<?php echo $item['adminId']; ?>"><?php echo $item['realName']; ?></a></td>
                                <td><?php echo $item['userName']; ?></td>
                                <td><?php echo $item['groupName']; ?></td>
                                <td>
                                <?php
                                    if ($item['status'] == 1) {
                                        echo '正常';
                                    } else {
                                        echo '已禁用';
                                    }
                                ?>
                                </td>
                            </tr>
                            <?php
                                }
                            } else {
                            ?>
                        <tr>
                            <td colspan="5">无数据！</td>
                        </tr>
                    <?php
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5"><?php echo $pagination; ?></td>
                    </tr>

                </tfoot>
            </table>
        </div>
    </form>
</div>
</div>