<!-- Fixed navbar -->
<?php
    $userInfo = unserialize(base64_decode($_COOKIE['_USERINFO']));

    $title = $userInfo['title'];
    
    //根据行业不同，切换不同的管理模块
    if(isset($_COOKIE['industry_modules']) && $_COOKIE['industry_modules']){
        $industry_modules = @$_COOKIE['industry_modules'];
    }else{
        $industry_modules = 'Default';
    }
?>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="javascript:void(0);"><span style="font-size: 24px;">家大.</span>小区服务</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="javascript:void(0);">您好，<?php echo $title;?></a></li>
                 
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="/Login/logout">退出</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>