
<!--Footer-part-->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!--action page additional files-->
<?php
    if (isset($_page['static_js_files']) && is_array($_page['static_js_files'])) {
        echo $this->_view->_js($_page['static_js_files']);
    }
?>
<!--全局文件-->
<script src="//<?php echo $static_domain;?>/plugin/jquery_treeview/lib/jquery.cookie.js" type="text/javascript"></script>
<script src="//<?php echo $static_domain;?>/plugin/jquery_treeview/jquery.treeview.js" type="text/javascript"></script>
<script src="//<?php echo $static_domain;?>/js/basic/libs/jquery.validate.js" charset="utf-8"></script>
<script src="//<?php echo $static_domain;?>/js/basic/form.js" charset="utf-8"></script>
<script src="//<?php echo $static_domain;?>/js/business/business.js" charset="utf-8"></script>
<script type="text/javascript">
    $(function() {
        $("#tree").treeview({
            collapsed: false,
            animated: "medium",
            control: "#sidetreecontrol",
            persist: "location"
        });
    })
//$(document).ready(function() {
//    var form = $('form.validate');
//    if (form.length) {
//        form.each(function() {
//            //弹层显示错误
//            autoValidate(this);
//        });
//    }
//    页面内显示错误
//        $("#form").validate({
//            debug: true,
//            errorElement: "div",
//            errorPlacement: function(error, element) {
//                $(".showmsg").html(error);
//            }
//        });

//});
</script>
<?php
//添加、修改等事件发生后弹出消息
if (isset($_event)) {
    $this->_view->jsRedirect($_event);
}
?>