<!DOCTYPE html>
<html>
    <head>
        <title>家大.商家后台管理系统</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="//static.jiada.local/plugin/bootstrap303/css/bootstrap.min.css">
        <link rel="stylesheet" href="//static.jiada.local/plugin/jquery_treeview/jquery.treeview.css" />
        <link rel="stylesheet" href="//static.jiada.local/admin/css/jiada.css" />
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <script src="//static.jiada.local/admin/js/jquery.min.js"></script>
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
            <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--top-Header-menu-->
        <?php include_once 'layout_header.phtml'; ?>

        <!--close-top-Header-menu-->


        <div class="container">
            <div class="row" style="padding-top: 60px;">
                <div id="left" class="col-md-3">
                    <!--sidebar-menu-->
                    <?php include_once 'layout_left.phtml'; ?>

                </div>
                <div id="right" class="col-md-9 nopadding">
                    <!--main-container-part-->
                    <div class="content">
                        <!--Action boxes-->
                        <?php
                        echo $_ActionContent;
                        ?>
                        <!--End Action boxes-->
                    </div>
                </div>
            </div>


        </div>
        <!--Footer-part-->
        <?php include_once 'layout_footer.phtml'; ?>

    </body>
</html>