<!-- Fixed navbar -->
<?php
    $userInfo = unserialize(base64_decode($_COOKIE['_USERINFO']));
    

    if(isset($currentShopId) && $currentShopId){
        $logoLink="/$industry_modules/Shop/index/shopId/$currentShopId";
    }else{
        $logoLink="/$industry_modules/Index/index";
    }
    
    if(isset($_COOKIE['shopId']) && isset($_COOKIE['acl']) && $_COOKIE['shopId'] && $_COOKIE['acl']){
        $title = @$userInfo['realName'];
    }else{
        $title = @$userInfo['title'];
        $logoLink="/$industry_modules/Index/index";
    }
    
?>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $logoLink;?>"><span style="font-size: 22px;">家大小区服务.</span><small>商家后台</small></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown">欢迎您：<?php echo $title;?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/Chaoshi/Bizmanage/edit">商家信息</a></li>                        
                        <li class="divider"></li>
                        <li><a href="/Chaoshi/Shop/add">新建店铺</a></li>
                    </ul>
                </li>
                <?php
                    if(isset($currentShopId) && $currentShopId){
                ?>
                 <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown">当前店铺：<?php echo $currentShopInfo['shopName'];?> <b class="caret"></b></a>
                    <?php
                        if(isset($businessShops) && $businessShops){
                    ?>
                    <ul class="dropdown-menu">
                        <?php
                            foreach($businessShops as $key=>$item){
                                if(count($businessShops)>1){
                                    if($currentShopId == $item['shopId']) continue;
                                }
                        ?>
                        <li><a href="<?php echo "/$industry_modules/Shop/index/shopId/$item[shopId]";?>"><?php echo $item['shopName'];?></a></li>
                        <?php
                            }
                        ?>
                    </ul>
                    <?php
                        }
                    ?>
                </li>
                <?php
                    }
                ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">商家服务<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a >客服电话：010-6888888</a></li>
                        <li><a >投诉建议：isgiker@gmail.com</a></li>

                    </ul>
                </li>
                <li><a href="/Login/logout">退出</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>