<!--sidebar-menu-->
<?php
//根据shopid判断调用商家的左侧菜单还是店铺的左侧菜单
if (isset($currentShopId) && $currentShopId) {
    $menuName = 'Shop';
} else {
    $menuName = 'Business';
}
//$leftMenu
include_once CONFIG_PATH . DS . 'business_leftmenu.php';

?>
<div id="sidetree" class="breadcrumb">
    <div id="sidetreecontrol"><a href="?#">折叠</a> | <a href="?#">展开</a></div>
    <ul id="tree" class="list-group">
        
        <?php
            if(isset($leftMenu[$industry_modules][$menuName]) && $leftMenu[$industry_modules][$menuName] && is_array($leftMenu[$industry_modules][$menuName])){
                foreach ($leftMenu[$industry_modules][$menuName] as $key => $menus) {

        ?>
        <li><span><?php echo $key;?></span>
            <ul>
                <?php 
                if($menus && is_array($menus)){
                        foreach ($menus as $mName => $mLink) {
                            if ($mLink == 'keep_spacing') {
                                    echo '</ul><ul>';
                                    continue;
                                }
                ?>
                <li><a href="<?php echo $mLink;?>"><?php echo $mName;?></a></li>
                <?php
                                   
                        }
                }
                ?>
            </ul>

        </li>
        <?php
                }
            }
        ?>
    </ul>
</div>
<!--sidebar-menu-->