<div class="content">
    <div class="mod_order_head">
        <font class="tit">我的订单</font>
        <div class="recpt_bor"></div>
    </div>
    <div class="mod_order_list">
        <?php
 
            if(isset($data['orderNoList']) && $data['orderNoList']){
                foreach($data['orderNoList'] as $k=>$orNo){
                    $year=date('Y',$orNo['createTime']);
                    $month=date('m',$orNo['createTime']);
                    $day=date('d',$orNo['createTime']);
                    $payAmount=  explode('.', $orNo['payAmount']);
        ?>
        
        <div class="order">
            <div class="order_left">
                <?php
                    $orderTotal=count($data['orderList'][$orNo['orderNo']]);
                    if(isset($data['orderList'][$orNo['orderNo']]) && $data['orderList'][$orNo['orderNo']]){
                        foreach($data['orderList'][$orNo['orderNo']] as $key=>$item){
                            $year=date('Y',$orNo['createTime']);
                            $month=date('m',$orNo['createTime']);
                            $day=date('d',$orNo['createTime']);
                            $payAmount=  explode('.', $orNo['payAmount']);
                ?>
                <p class="order_link">
                    <a href="javascript:void(0);" class="icon_order" target="_blank">包裹1</a>
                    <font>来自</font>
                    <a href="javascript:void(0);" target="_blank" >家大自营</a>
                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                    <a href="javascript:void(0);" target="_blank" class="black_line">已完成</a>
                </p>
                <p class="order_screen_list">
                    <?php
                        if(isset($item['product_list']) && $item['product_list']){
                            foreach($item['product_list'] as $p){
                                if (isset($p['packPic']) && $p['packPic']) {
                                    $pics = explode(',', $p['packPic']);
                                    $firstPic = $pics[0];
                                    $goodsPic = $fileImg_obj->generateImgUrl(array('imgSize' => '60X60', 'imgUrl' => $firstPic), $imagesConfig);
                                } else {
                                    $goodsPic = '';
                                }
                            
                    ?>
                    <a class="pa" href="<?php echo '//' . $_config_domain['chaoshi'].'/detail?p='.$p['priceId'];?>" target="_blank" title="<?php echo $p['productName'];?>">
                        <img src="<?php echo $goodsPic;?>">
                        <br />
                        <span><strong>¥<?php echo $p['currentPrice'];?></strong>x<?php echo $p['productNum'];?></span>
                    </a>
                    <?php
                            }
                        }
                    ?>
                </p>
                <?php
                    if($orderTotal > 1 && ($key+1)<$orderTotal){
                        echo '<hr size="1">';
                    }
                ?>
                <?php
                        }

                    }
                ?>
                
                <div class="clr"></div>
            </div>
            <div class="order_right">

                <ul>
                    <li class="ordering_time">
                        <span class="year"><?php echo $year;?></span>
                        <span class="month"><?php echo $month;?>/<?php echo $day;?></span><br>
                    </li>
                    <li class="order_num">
                        订单号：<?php echo $orNo['orderNo'];?>
                    </li>
                    <li class="order_amount">
                        <span class="price_sen">¥</span>
                        <span class="price"><?php echo $payAmount[0];?>.</span>
                        <span class="price_sen"><?php echo $payAmount[1];?></span>
                    </li>
                    <li class="order_operating">
                        <a href="javascript:void(0);" class="default_btn">再次购买</a>
                        <a href="javascript:void(0);" class="default_btn blue" target="_blank">查看订单</a>

                    </li>
                </ul>
            </div>
            <div class="clr"></div>
        </div>
        <?php
                }
            }
        ?>
        
        <div class="clr"></div>
    </div>
</div>