
<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">用户组管理</a> </li>
    <li class="active">添加</li>
</ul>


<!--End-breadcrumbs-->
<div class="widget-box">
    <div class="widget-title">
        <h5>Admin Group-info</h5>
    </div>
    <div class="widget-content nopadding">
        <form name="form" id="form" action="" method="post" class="form-horizontal validate">
            <div class="form-group control-group">
                <label for="parentId" class="col-sm-2 control-label">父分类：</label>
                <div class="col-sm-10">
                    <select name="parentId" id="parentId" <?php echo $this->_view->getInputAttrs($rules, 'parentId') ?> class="form-control">
                        <option value="0" selected>顶级</option>
                        <?php echo $treeAgroup; ?>
                    </select>
                    <div class="showmsg">
                        <?php
                        if (isset($error['parentId'])) {
                            $this->_view->showValidateError($error['parentId']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">用户组：</label>
                <div class="col-sm-10">
                    <input type="text" name="groupName" <?php echo $this->_view->getInputAttrs($rules, 'groupName') ?> id="groupName" value="<?php if (isset($post['groupName'])) echo $post['groupName'] ?>"  class="form-control" placeholder="管理员 数据维护员" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['groupName'])) {
                            $this->_view->showValidateError($error['groupName']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2  textRight">继承父类权限：</label>
                <div class="col-sm-10">
                    <input type="checkbox" name="extends" id="extends" value="1" />
                </div>
            </div>
            <div class="form-group control-group">
                <label for="status" class="col-sm-2 textRight">是否公开：</label>
                <div class="col-sm-10">
                    <label>
                        <input type="radio" name="status" value="1" checked <?php
                        if (isset($post['status'])) {
                            if ($post['status'] == 1) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        }
                        ?>/>
                        是
                    </label>
                    <label>
                        <input type="radio" name="status" value="-1" <?php
                        if (isset($post['status'])) {
                            if ($post['status'] == -1) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        }
                        ?>/>
                        否 
                    </label>
                </div>
            </div>
            <div class="form-group control-group">
                <div class="col-sm-12">
                    <table class="table table-bordered table-hover">
                        <?php
                        $_acl = array();
                        if (isset($post['acl']) && $post['acl']) {
                            $_acl = $post['acl'];
                        }
                        if (isset($resourcConfig) && $resourcConfig) {
                            foreach ($resourcConfig as $m => $rv) {
                                echo '<thead><tr><td colspan="2">'.$rv['name'].'</td></tr></thead>';
                                foreach ($rv as $c => $item) { 
                                    if(is_string($item))continue;
                                    ?>
                                    <tr>
                                        <td class="col-sm-2" style="text-align: right;"><?php echo $item['name']; ?></td>
                                        <td>
                                            <?php
                                            foreach ($item as $a => $eventName) {
                                                if ($a == 'name')
                                                    continue;
                                                $acl = $m . '.' . $c . '.' . $a;
                                                ?>
                                            <span style="margin-right: 10px;">
                                                <input type="checkbox" name="acl[]" value="<?php echo $acl; ?>" <?php if (!empty($_acl) && in_array($acl, $_acl)) {
                                    echo ' checked';
                                } ?>/> <?php echo $eventName; ?>
                                            </span>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                    <?php
                                }
                            }
                        }
                        ?>

                    </table>
                    
                </div>
            </div>
            <div class="form-actions">
                <label for="button" class="col-sm-2 control-label"></label>
                <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
            </div>
        </form>
    </div>
</div>
