<!--sidebar-menu-->

<div class="mod_personal_info">
    <blockquote class="user_img">
        <a href="javascript:void(0);">
            <img alt="用户头像" src="<?php echo '//' . $_config_domain['static'] . '/img/basic/member_01.gif'; ?>">
            <span><u>编辑资料</u></span>
        </a>
    </blockquote>
    <blockquote class="user_info">
        <p><strong><a id="leftendUserName" href="javascript:void(0);">姜豆儿的妈</a></strong></p>
        <p><span class="pV1"><a href="javascript:void(0);">会员等级:V1</a></span></p>
    </blockquote>
</div>
<div class="mod_personal_menu">
    <div class="services_personal_center">
        <dl>
            <dt><span class="tit_big">交易中心</span></dt>
            <dd><a class="selected" href="/order/myOrder.do" onclick="addTrackPositionToCookie('2', 'O_L_MYORDER')">我的订单</a></dd>
            <dd><a href="http://www.yhd.com/dqg/mysubscribe/mydqg.do">我的定期购</a></dd>
            <dd><a href="/member/trialCenter/myTrail.do" onclick="addTrackPositionToCookie('2', 'O_L_MYTRAIL')">我的试用品</a></dd>
            <dd><a href="/member/exp/comment.do" onclick="addTrackPositionToCookie('2', 'O_L_MYCOMMENT')">评论商品</a></dd>
            <dd><a href="/member/myNewCollection/myFavorite.do" onclick="addTrackPositionToCookie('2', 'O_L_MYCOLLECTION')">我的收藏</a></dd>
            <dd><a href="http://life.yhd.com/lottery/displayMyLottery.do" onclick="addTrackPositionToCookie('2', 'O_L_MYORDER')">我的彩票</a></dd>
            <dd>
                <hr size="1">
            </dd>
            <dd><a href="/account/displayAccount.do" onclick="addTrackPositionToCookie('2', 'O_L_MYDISPLAYACCOUNT')">账户余额</a></dd>
            <dd><a href="/points/displayPointAccount.do" onclick="addTrackPositionToCookie('2', 'O_L_MYDISPLAYPOINT')">我的积分</a></dd>
            <dd><a href="/giftcard/displayGiftCardAddMoney.do" onclick="addTrackPositionToCookie('2', 'O_L_MYDISPLAYGIFT')">我的礼品卡</a></dd>
            <dd><a href="http://www.yhd.com/myCoupon/" onclick="addTrackPositionToCookie('2', 'O_L_MYDISPLAYCOUPONS')">我的抵用券</a></dd>

            <dt><span class="tit_big">服务中心</span></dt>
            <dd><a href="http://help.yhd.com/opinion/opinionList.do" onclick="addTrackPositionToCookie('2', 'O_L_MYOPINION')">在线投诉</a></dd>
            <dd><a href="http://yas.yhd.com/return/returnApplyList.do" onclick="addTrackPositionToCookie('2', 'O_L_MYRETURNAPPLY')">在线退换货</a></dd>
            <dd><a href="/invoice/invoiceApply.do" onclick="addTrackPositionToCookie('2', 'O_L_MYINVOICEAPPLY')">发票管理</a></dd>
            <dd>
                <hr size="1">
            </dd>
            <dt><span class="tit_big">会员中心</span></dt>
            <dd><a href="/member/userinfo/editinfo.do" onclick="addTrackPositionToCookie('2', 'O_L_MYEDITINFO')">个人资料</a></dd>
            <dd><a href="http://vip.yhd.com/badge.html">我的勋章</a></dd>
            <dd><a href="/babyCenter/babyCoupon.do">母婴任务</a></dd>
            <dd><a href="/member/presents.do">我的赠品</a></dd>
            <dd><a href="/member/address/addressBook.do" onclick="addTrackPositionToCookie('2', 'O_L_MYADDRESSBOOK')">地址管理</a></dd>
            <dd><a href="/member/safecenter/index.do" onclick="addTrackPositionToCookie('2', 'O_L_MYCHANGEPW')">安全设置</a></dd>
            <dd><a href="/member/innerMessageNew/innerMessageNew.do" onclick="addTrackPositionToCookie('2', 'O_L_INNERMESSAGENEW')">我的消息</a></dd>
            <dd><a href="/vip/myVip.do">我的联名卡</a></dd>
            <dd>
                <hr size="1">
            </dd>
            <dd><a href="http://b2beam.yhd.com/b2b/upGradeToB2b.do" onclick="addTrackPositionToCookie('2', 'B2B_U_BEENTERPRISEUSER')">升级为企业用户</a></dd>
        </dl>
    </div>
</div>
<!--sidebar-menu-->