<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>BusAP APP 接口测试程序 v1.4</title>
</head>
<script src="/templates/help/js/jquery-1.6.js"></script>
<script>
jQuery.jtpc=jQuery.JTPC=function(obj,parameter,callback){
		parameter.obj=obj;
		parameter.url=location.href;
		$.ajax({
			url:'/interface.php',
			type:'post',
			data:parameter,
			success:function(data){
				if(data.match(/Error:/i)){
					alert(data);
				}else{
					callback(data);
				}
			}
		});
	};
	
$(document).ready(function(){
	$("#testbutton").click(function(){
		obj=$("#obj").val();
		parameter=$("#parameter").val();	
		
		$.JTPC(obj,$.parseJSON(parameter),function(result){
			$("#StrJson").text(result);
			$("#StrJson").slideDown("slow");
			$("#JsonViewerIframe").attr('src','/templates/help/jsonviewer.htm');
			$("#JsonViewerIframe").slideDown("slow");
			$("#help").fadeOut("slow");
		});
		//$("#efficiencyAnalysis").attr('href','http://xhprof.busap.cn/xhprof_html/index.php?run='+obj+'&source=xhprof');
		//$("#efficiencyAnalysis").html(obj+'性能分析');
	});
	$(document).keydown(function(event){
		if(event.keyCode==27){
			$("#help").fadeOut("slow");
		}
	});
	moduleList();
});

function resultToIframe(){
	return $("#StrJson").text();
}
function setObjValue(obj,parameter){
	$("#obj").val(obj);
	$("#parameter").val(decodeURIComponent(parameter));
	$("#efficiencyAnalysis").attr('href','');
	$("#efficiencyAnalysis").html("");
}

function help(className){
	$("#help").load('help.php?'+className,function(){
		$("#help").fadeIn("slow");
		$("#help").animate( { width: "391"}, { queue: false, duration: 'slow' } );
	});

}

function moduleList(){
	$("#list").load('list.php',function(){
		$("#list").fadeIn("slow");
		$("#list").animate( { height: "605"}, { queue: false, duration: 'slow' } );
		help('');
	});
}
</script>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="5">
	<tr>
		<td width="550" height="150" valign="top">
		<div style="border:solid; padding:5px">
		<font size="+2">BusAP APP 接口测试程序 v1.4</font><br>
		说明：参数请书写标准json格式，例如：<font color="#FF0000">{"sid":"7","currentPage":"2"}</font>
		<br><br>
		调用方法：<input type="text" name="obj" id="obj" style="width:100%"/><br>
		参　　数：<input type="text" name="parameter" id="parameter" value="{}" style="width:100%" />
		<br>
		<input value="测试JTPC" id="testbutton" type="button"><input value="方法速查" onclick="moduleList();" type="button">
		<a id="efficiencyAnalysis" href="" target="_blank"></a>
		</div></td>
		<td rowspan="2" valign="top"><iframe id="JsonViewerIframe" width="100%" height="815" style="display:none"></iframe></td>
	</tr>
	<tr id="viewer">
		<td valign="top">
                    <div id="list" style=" padding:10px;display:none;height:605px;width:100px; left: 5px;position: fixed;top: 201px;z-index: 1002; background: #ddd; border:solid;overflow:auto"></div>
                    <div style="border:solid; width:411px; height:625px;display:none;overflow:auto; margin-left:123px;left: 13px;float: right;position: fixed;top: 201px;z-index: 1002; " id="StrJson"></div></td>
	</tr>
</table>

<div id="help" style=" padding:10px;display:none;height:605px;width:0px;margin-left:123px;left: 13px;position: fixed;top: 201px;z-index: 1002; background: #ddd; border:solid;overflow:auto"></div>
</body>
</html>