<!DOCTYPE html>
<html>
    <head>
        <title>订单结算 - 家大小区超市</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="<?php echo '//' . $_config_domain['static'] . '/css/front-end/chaoshi/v1/chaoshi_common.css'; ?>">
        <link rel="stylesheet" href="<?php echo '//' . $_config_domain['static'] . '/css/front-end/chaoshi/v1/chaoshi_order.css'; ?>">
    </head>
    <body>
        <div class="w w1 header clearfix">
            <div id="logo">
                <a href="http://www.jd.com/">
                    <img src="http://misc.360buyimg.com/lib/img/e/logo-201305.png" title="返回家大首页" alt="返回家大首页">
                </a>
            </div>
            <div class="progress clearfix">
                    <ul class="progress-1">
                            <li class="step-1"><b></b>1.我的购物车</li>
                            <li class="step-2"><b></b>2.填写核对订单信息</li>
                            <li class="step-3">3.成功提交订单</li>
                    </ul>
            </div>
        </div>
        
        <div class="w m2">
            <div id="checkout">
                <div class="mt">
                    <h2>填写并核对订单信息</h2>
                </div>
                <div class="checkout-steps">
                    <div id="step-1" class="step step-complete">
                        <div class="step-title">
                            <div id="save-consignee-tip" class="step-right">
                            </div>
                            <strong id="consigneeTitleDiv">收货人信息</strong>
                            <span class="step-action" id="consignee_edit_action"><a href="#none" onclick="editConsignee()">[修改]</a></span>
                        </div>
                        <div class="step-content">
                            <div id="consignee" class="sbox-wrap">
                                <div class="sbox">
                                    <div class="s-content">
                                        <input type="hidden" id="hideAreaIds" value="10-698-702-46144"><!--icon隐藏域-->
                                        <p>
                                            <?php
                                                if(isset($defaultAddress) && $defaultAddress){
                                                    echo $defaultAddress['contact'].'&nbsp;'.$defaultAddress['mobile'].'&nbsp;  &nbsp;'.$defaultAddress['email'];
                                                    echo '<br>';
                                                    echo $areas[$defaultAddress['provinceId']]['areaName'].' '.$areas[$defaultAddress['cityId']]['areaName'].' '.$areas[$defaultAddress['districtId']]['areaName'].' '.$areas[$defaultAddress['communityId']]['areaName'];
                                                    echo '&nbsp;'.$defaultAddress['address'];
                                                }
                                            ?>

                                        </p>
                                    </div>
                                </div>						</div><!--@end div#consignee-->
                        </div>
                    </div>
                    <div id="step-2" class="step step-complete"><a name="payAndShipFocus"></a>
                        <div class="step-title">
                            <div id="save-payAndShip-tip" class="step-right">
                            </div>
                            <strong>支付及配送方式</strong>
                            <span class="step-action" id="payment-ship_edit_action"><a href="#none" onclick="edit_Payment(false)">[修改]</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <script src="<?php echo '//' . $_config_domain['static'] . '/js/basic/libs/jquery.min.js'; ?>"></script>
        <script src="<?php echo '//' . $_config_domain['static'] . '/js/front-end/chaoshi/v1/chaoshi_common.js'; ?>" type="text/javascript" ></script>
        <script src="<?php echo '//' . $_config_domain['static'] . '/js/front-end/chaoshi/v1/chaoshi.js'; ?>" type="text/javascript" ></script>
        <script src="<?php echo '//' . $_config_domain['static'] . '/js/front-end/chaoshi/v1/chaoshi_order.js'; ?>" type="text/javascript" ></script>
        
    </body>
</html>