<form class="form-horizontal validate" method="post" id="loginForm">
    <div class="form-group">
        <label  class="col-md-3 control-label">用户名:</label>
        <div class="col-md-8">
            <input type="text" class="form-control" <?php echo $this->_view->getInputAttrs($rules, 'username') ?> placeholder="用户名">
        </div>
        <div class="col-md-8 col-md-offset-3 showmsg">
            <?php
            if (isset($error['username'])) {
                $this->_view->showValidateError($error['username']);
            }
            ?>
        </div>
    </div>
    <div class="form-group">
        <label  class="col-md-3 control-label">密码:</label>
        <div class="col-md-8">
            <input type="password" class="form-control" <?php echo $this->_view->getInputAttrs($rules, 'password') ?> placeholder="密码">
        </div>
        <div class="col-md-8 col-md-offset-3 showmsg">
            <?php
            if (isset($error['password'])) {
                $this->_view->showValidateError($error['password']);
            }
            ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <button type="submit" class="btn btn-danger">登录</button>
            <input type="button" class="btn btn-primary" onclick="$('#loginForm')[0].reset();" value="重置"/>
            <a href="" class="btn btn-warning">忘记密码</a>
        </div>
    </div>
</form>
