<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">商家管理</a> </li>
    <li class="active">列表</li>
</ul>


<div class="widget-list">
    <form name="jform" id="jform" action="" method="post" class="form-horizontal">
        
        
        <div class="widget-content ">
            <div class="search">
                <span class="col-sm-2 nopadding">
                    <select name="status" class="form-control input-sm">
                        <option value="all" <?php
                        if (isset($post['status']) && $post['status'] == 'all') {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>显示所有</option>
                        <option value="1" <?php
                        if ((isset($post['status']) && $post['status'] == 1) || (isset($post['status']) && $post['status'] =='')) {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>审核通过</option>
                        <option value="-1" <?php
                        if (isset($post['status']) && $post['status'] == -1) {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>等待审核</option>
                        <option value="-2" <?php
                        if (isset($post['status']) && $post['status'] == -2) {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>关闭</option>
                    </select>
                </span>

                <span>
                    <button type="submit" name="jsubmit" value="search" class="btn btn-default btn-sm" >检索</button>
                </span>
            </div>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                        <th>商家名称</th>
                        <th>地区</th>
                        <th>所属行业</th>
                        <th>联系人</th>
                        <th>联系手机</th>
                        <th>状态</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (is_array($data) && !empty($data)) {
                        foreach ($data as $key => $item) {
                            ?>
                            <tr>
                                <td class="checkids"><input type="checkbox" name="checkIds[]" value="<?php echo $item['businessId']; ?>"/></td>
                                <td><a href="/Default/Business/edit/businessId/<?php echo $item['businessId']; ?>"><?php echo $item['title']; ?></a></td>
                                <td><?php if(isset($item['areaNames']))echo $item['areaNames']; ?></td>
                                <td><?php echo $item['industryId']; ?></td>
                                <td><?php echo $item['contact']; ?></td>
                                <td><?php echo $item['mobile']; ?></td>
                                <td><?php 
                                //1 审核通过 ，-1等待审核，-2关闭
                                if($item['status']==1){
                                    echo '审核通过';
                                }elseif($item['status']==-1){
                                    echo '等待审核';
                                }elseif($item['status']==-2){
                                    echo '关闭';
                                }
                                ?></td>
                            </tr>
                            <?php
                        }
                    } else {
                        ?>
                        <tr>
                            <td colspan="7">无数据！</td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7"><?php echo $pagination; ?></td>
                    </tr>

                </tfoot>
            </table>
        </div>
    </form>
</div>
