
<!--breadcrumbs-->
<div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#" class="tip-bottom">商品属性</a> <a href="#" class="current">添加</a> </div>
    <h1>商品属性管理</h1>
</div>

<!--End-breadcrumbs-->
<div class="container-fluid">
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li><a href="/admin/goodsattrcate/index/cateId/<?php echo $goodsCateId;?>">商品属性分类管理</a></li>
                        <li class="active"><a href="/admin/goodsattr/index/cateId/<?php echo $goodsCateId;?>">商品属性管理</a></li>
                    </ul>
                </div>
                <div class="widget-content nopadding tab-content">
                    <div id="tab1" class="tab-pane">

                    </div>
                    <div id="tab2" class="tab-pane active">
                        <form action="/admin/goodsattr/add" name="jform" id="jform" method="post" class="form-horizontal">
                            <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 商品分类 :</label>
                                <div class="controls">
                                    <input type="text" name="cateName" id="cateName" value="<?php echo $gcateInfo['cateName'] ?>" class="span5"  readonly />
                                    <input type="hidden" name="goodsCateId" <?php echo $this->_view->getInputAttrs($rules, 'goodsCateId') ?> id="cateId" value="<?php echo $gcateInfo['cateId'] ?>" class="span5"   readonly/>
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['goodsCateId'])) {
                                            $this->_view->showValidateError($error['goodsCateId']);
                                        }
                                        ?>
                                    </div>
                                </div>

                            </div>
                            <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 属性分类 :</label>
                                <div class="controls">
                                    <select name="attrCateId" class="span5">
                                        <?php
                                            foreach ($goodsAttrCate as $k => $v) {
                                        ?>
                                        <option value="<?php echo $v['attrCateId'];?>" ><?php echo $v['attrCateName'];?></option>
                                        <?php
                                           }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 属性名称 :</label>
                                <div class="controls">
                                    <input type="text" name="attrName" <?php echo $this->_view->getInputAttrs($rules, 'attrName') ?> id="attrCateName" value="" class="span5" placeholder="如：作者 出版日期" />
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['attrName'])) {
                                            $this->_view->showValidateError($error['attrName']);
                                        }
                                        ?>
                                    </div>
                                </div>

                            </div>
                            <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 属性值录入方式 :</label>
                                <div class="controls">
                                    <select name="attrInputType" class="span5">
                                        <option value="text" selected>文本【text】</option>
                                        <option value="select" >下拉框【select】</option>
                                        <option value="checkbox" >复选【checkbox】</option>
                                        <option value="radio" >单选【radio】</option>
                                        <option value="textarea" >大文本【textarea】</option>                                        
                                    </select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">可选值列表 :</label>
                                <div class="controls">
                                    <textarea name="attrValues" <?php echo $this->_view->getInputAttrs($rules, 'attrValues') ?> placeholder="多个值敲回车分隔；如果录入方式是：select checkbox radio，此项必填！" class="span5" rows="6"></textarea>                                    
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['attrValues'])) {
                                            $this->_view->showValidateError($error['attrValues']);
                                        }
                                        ?>
                                    </div>
                                </div>

                            </div>
                            <div class="control-group">
                            <label class="control-label">是否必填项 :</label>
                            <div class="controls">
                                <label>
                                    <input type="radio" name="isRequired" value="1" <?php if(isset($post['isRequired'])){ if($post['isRequired']==1){echo ' checked';}else{ echo ' ';}}?>/>
                                    是
                                </label>
                                <label>
                                    <input type="radio" name="isRequired" value="0" checked <?php if(isset($post['isRequired'])){ if($post['isRequired']==0){echo ' checked';}else{ echo ' ';}}?>/>
                                    否 
                                </label>
                            </div>
                        </div>
                            <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 排序 :</label>
                                <div class="controls">
                                    <input type="text" name="sort" <?php echo $this->_view->getInputAttrs($rules, 'sort') ?> id="sort" value="" class="span5" placeholder="01 02 03" />
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['sort'])) {
                                            $this->_view->showValidateError($error['sort']);
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success" onclick="ajaxForm('jform');
                                        return false;">Save</button>
                                <button type="reset" class="btn btn-primary">Reset</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>



        </div>

    </div>

</div>
