<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index/cateId/$gcateInfo[cateId]" ?>">商品属性管理</a> </li>
    <li class="active">编辑</li>
</ul>


<!--End-breadcrumbs-->
<div class="widget-box">
    <div class="widget-title">
        <h5>Goods Attribute-info</h5>
    </div>
    <div class="widget-content nopadding">
        <form action="" method="post" class="form-horizontal validate">
            <div class="form-group control-group">
                <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品分类 :</label>
                <div class="col-sm-10">
                    <input type="text" name="cateName" id="cateName" value="<?php echo $gcateInfo['cateName']; ?>" class="form-control"  readonly />
                    <input type="hidden" name="goodsCateId" <?php echo $this->_view->getInputAttrs($rules, 'goodsCateId') ?> id="cateId" value="<?php echo $gcateInfo['cateId']; ?>" class="form-control"   readonly/>
                    <div class="showmsg">
                        <?php
                        if (isset($error['goodsCateId'])) {
                            $this->_view->showValidateError($error['goodsCateId']);
                        }
                        ?>
                    </div>
                </div>

            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label"> <b class="bold red">*</b> 属性分类 :</label>
                <div class="col-sm-10">
                    <select name="attrCateId" class="form-control">
                        <?php
                        foreach ($goodsAttrCate as $k => $v) {
                            ?>
                            <option value="<?php echo $v['attrCateId']; ?>" <?php if ($v['attrCateId'] == $gAttrInfo['attrCateId']) {
                            echo ' selected';
                        } ?>><?php echo $v['attrCateName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label"> <b class="bold red">*</b> 属性名称 :</label>
                <div class="col-sm-10">
                    <input type="text" name="attrName" <?php echo $this->_view->getInputAttrs($rules, 'attrName') ?> id="attrCateName" value="<?php echo $gAttrInfo['attrName']; ?>" class="form-control" placeholder="如：作者 出版日期" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['attrName'])) {
                            $this->_view->showValidateError($error['attrName']);
                        }
                        ?>
                    </div>
                </div>

            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label"> <b class="bold red">*</b> 属性值录入方式 :</label>
                <div class="col-sm-10">
                    <select name="attrInputType" class="form-control">
                        <option value="text" <?php if ('text' == $gAttrInfo['attrInputType']) {
                            echo ' selected';
                        } ?>>文本【text】</option>
                        <option value="select" <?php if ('select' == $gAttrInfo['attrInputType']) {
                            echo ' selected';
                        } ?>>下拉框【select】</option>
                        <option value="checkbox" <?php if ('checkbox' == $gAttrInfo['attrInputType']) {
                            echo ' selected';
                        } ?>>复选【checkbox】</option>
                        <option value="radio" <?php if ('radio' == $gAttrInfo['attrInputType']) {
                            echo ' selected';
                        } ?>>单选【radio】</option>
                        <option value="textarea" <?php if ('textarea' == $gAttrInfo['attrInputType']) {
                            echo ' selected';
                        } ?>>大文本【textarea】</option>                                        
                    </select>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">可选值列表 :</label>
                <div class="col-sm-10">
                    <textarea name="attrValues" placeholder="多个值敲回车分隔；如果录入方式是：select checkbox radio，此项必填！" class="form-control" rows="6"><?php echo $gAttrInfo['attrValues']; ?></textarea>                                    

                </div>

            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">是否必填项 :</label>
                <div class="col-sm-10">
                    <label>
                        <input type="radio" name="isRequired" value="1" <?php if (isset($gAttrInfo['isRequired'])) {
    if ($gAttrInfo['isRequired'] == 1) {
        echo ' checked';
    } else {
        echo ' ';
    }
} ?>/>
                        是
                    </label>
                    <label>
                        <input type="radio" name="isRequired" value="0" checked <?php if (isset($gAttrInfo['isRequired'])) {
                            if ($gAttrInfo['isRequired'] == 0) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        } ?>/>
                        否 
                    </label>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label"> <b class="bold red">*</b> 排序 :</label>
                <div class="col-sm-10">
                    <input type="text" name="sort" <?php echo $this->_view->getInputAttrs($rules, 'sort') ?> id="sort" value="<?php echo $gAttrInfo['sort']; ?>" class="form-control" placeholder="0 1 2 3" />
                    <div class="showmsg">
                    <?php
                    if (isset($error['sort'])) {
                        $this->_view->showValidateError($error['sort']);
                    }
                    ?>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <label for="button" class="col-sm-2 control-label"></label>
                <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
            </div>
        </form>
    </div>
</div>