<!--breadcrumbs-->
<div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="/Admin/Goods/index" class="tip-bottom">商品</a> <a href="javascript:void(0);" class="current">列表</a> </div>
    <h1>商品管理</h1>
</div>
<div class="container-fluid">
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                
                    <div class="widget-title">
                        <span class="icon"> <i class="icon-th"></i> </span>
                        <span class="submenu right"><button type="submit" name="jsubmit" value="del" class="btn" >删除</button></span>
                        <span class="submenu right"><button type="submit" name="jsubmit" value="search" class="btn" onclick="location.href='/Admin/Goods/add';">添加商品</button></span>
                    </div>
                    <div class="widget-content ">
                        <form name="jform" id="jform" action="" method="post" class="form-horizontal">
                        <div class="search">
                            <span>
                                <select name="onLine" class="span2">
                                    <option value="all" <?php if($post['onLine']==''){echo ' selected';}else{echo '';}?>>显示所有</option>
                                    <option value="1" <?php if(isset($post['onLine']) && $post['onLine']==1){echo ' selected';}else{echo '';}?>>已上架</option>
                                    <option value="0" <?php if(isset($post['onLine']) && $post['onLine']===0){echo ' selected';}else{echo '';}?>>已下架</option>
                                </select>
                            </span>
                            
                            <span><button type="submit" name="jsubmit" value="search" class="btn" >搜索</button></span>
                            
                        </div>
                        
                        
                        <table class="table table-bordered table-striped with-check">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                                    <th>商品名称</th>
                                    <th>商品分类</th>
                                    <th>商品品牌</th>
                                    <th>现价</th>
                                    <th>发布时间</th>
                                    <th>状态</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (is_array($data) && !empty($data)) {
                                    foreach ($data as $key => $item) {
                                        ?>
                                        <tr>
                                            <td><input type="checkbox" name="checkIds[]" value="<?php echo $item['goodsId']; ?>"/></td>
                                            <td><a href="/Admin/Goods/edit/goodsId/<?php echo $item['goodsId']; ?>"><?php echo $item['goodsNme']; ?></a></td>
                                            <td><?php echo $item['cateId']; ?></td>
                                            <td><?php echo $item['brandId']; ?></td>
                                            <td><?php echo $item['currentPrice']; ?></td>
                                            <td><?php echo date('Y-m-d H:i:s', $item['publishTime']); ?></td>
                                            <td><?php if($item['onLine']==1){ echo '已上架';}else{ echo '已下架';} ?></td>
                                        </tr>
                                        <?php
                                    }
                                } else {
                                    ?>
                                    <tr>
                                        <td colspan="7">无数据！</td>
                                    </tr>
                                    <?php
                                }
                                ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="7"><?php echo $pagination; ?></td>
                                </tr>

                            </tfoot>
                        </table>
                        </form>
                    </div>
                
            </div>


        </div>
    </div>
</div>

