<!--breadcrumbs-->
<div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="/Admin/Goods/index" class="tip-bottom">商品</a> <a href="#" class="current">价格</a> </div>
    <h1>商品价格管理</h1>
</div>

<!--End-breadcrumbs-->
<div class="container-fluid">
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <form action="" method="post" class="form-horizontal">
                    

                            <div class="control-group">
                                <label class="control-label">商品分类 :</label>
                                <div class="controls">
                                    <?php if(isset($goodsInfo['cateName'])){echo $goodsInfo['cateName'];}?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">商品品牌 :</label>
                                <div class="controls">
                                    <?php if(isset($goodsInfo['brandName'])){echo $goodsInfo['brandName'];}?>

                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">商品名称 :</label>
                                <div class="controls">
                                    <?php if(isset($goodsInfo['goodsNme'])){echo $goodsInfo['goodsNme'];}?>
                                </div>

                            </div>
                    <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 所属仓库 :</label>
                                <div class="controls">
                                    <select name="storehouseId" id="storehouseId" class="span5">                                        
                                        <?php
                                            if(isset($storehouse) && $storehouse){
                                                foreach ($storehouse as $key => $val) {
                                                    if(1==$val['storehouseId']){$selected=' selected';}else{$selected='';}
                                                    echo "<option value='".$val[storehouseId]."' $selected>".$val['storehouseName']."</option>";
                                                }
                                            }
                                        ?>
                                    </select>
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['storehouseId'])) {
                                            $this->_view->showValidateError($error['storehouseId']);
                                        }
                                        ?>
                                    </div>

                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 商品价格 :</label>
                                <div class="controls">
                                    <input type="text" name="originalPrice" <?php echo $this->_view->getInputAttrs($rules, 'originalPrice') ?> id="originalPrice" value="<?php if(isset($goodsInfo['originalPrice'])){echo $goodsInfo['originalPrice'];}?>" class="span2" placeholder="原价:本店售价" />
                                    <input type="text" name="discount" <?php echo $this->_view->getInputAttrs($rules, 'discount') ?> id="discount" value="<?php if(isset($goodsInfo['discount'])){echo $goodsInfo['discount'];}?>" class="span2" placeholder="折扣比例:0.85" />
                                    <input type="text" name="currentPrice" <?php echo $this->_view->getInputAttrs($rules, 'currentPrice') ?> id="currentPrice" value="<?php if(isset($goodsInfo['currentPrice'])){echo $goodsInfo['currentPrice'];}?>" class="span2" placeholder="现价:活动促销价格" />
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['originalPrice'])) {
                                            $this->_view->showValidateError($error['originalPrice']);
                                        }
                                        if (isset($error['discount'])) {
                                            $this->_view->showValidateError($error['discount']);
                                        }
                                        if (isset($error['currentPrice'])) {
                                            $this->_view->showValidateError($error['currentPrice']);
                                        }
                                        ?>
                                    </div>
                                </div>                            
                            </div>
                            <div class="control-group">
                                <label class="control-label">市场价格 :</label>
                                <div class="controls">
                                    <input type="text" name="marketPrice" <?php echo $this->_view->getInputAttrs($rules, 'marketPrice') ?> id="marketPrice" value="<?php if(isset($goodsInfo['marketPrice'])){echo $goodsInfo['marketPrice'];}?>" class="span2" placeholder="" />
                                    <div class="col-md-8 col-md-offset-3 showmsg">
                                        <?php
                                        if (isset($error['marketPrice'])) {
                                            $this->_view->showValidateError($error['marketPrice']);
                                        }
                                        ?>
                                    </div>
                                </div>                            
                            </div>

                            <div class="control-group">
                                <label class="control-label">活动促销 :</label>
                                <div class="controls">
                                    <input type="text" name="activityStartTime" id="activityStartTime" data-date="<?php echo date('Y-m-d H:i:s'); ?>" data-date-format="yyyy-mm-dd H:i:s" value="<?php if(isset($goodsInfo['activityStartTime'])){echo $goodsInfo['activityStartTime'];}?>" class="datepicker span3" placeholder="开始时间" />
                                    <input type="text" name="activityEndTime" id="activityEndTime" value="<?php if(isset($goodsInfo['activityEndTime'])){echo $goodsInfo['activityEndTime'];}?>" class="span3" placeholder="结束时间" />

                                </div>                            
                            </div>
                            <div class="control-group">
                                <label class="control-label">推荐标签 :</label>
                                <div class="controls">
                                    <?php
                                            $reTagsArr = array('1'=>'活动','2'=>'热销','3'=>'新品','4'=>'精品','5'=>'人气');
                                            if($goodsInfo['recTags']){
                                                echo $reTagsArr[$goodsInfo['recTags']];
                                            }
                                        ?> 
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"> <b class="bold red">*</b> 上架 :</label>
                                <div class="controls">
                                    <?php
                                        if (isset($goodsInfo['onLine'])) {
                                            if ($goodsInfo['onLine'] == 1) {
                                                echo '是';
                                            } else {
                                                echo '否';
                                            }
                                        }
                                        ?>
                                    
                                </div>
                            </div>



                            <div class="form-actions">
                                <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                                <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
                            </div>

                </form>
            </div>



        </div>

    </div>

</div>
