<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">仓库管理</a> </li>
    <li class="active">编辑</li>
</ul>

<!--End-breadcrumbs-->
<div class="widget-box">
    <div class="widget-title">
        <h5>Storehouse-info</h5>
    </div>
    <div class="widget-content nopadding">
        <form action="" method="post" class="form-horizontal validate">
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">所在地区 :</label>
                <div class="col-sm-10">
                    <span class="col-md-3 ">
                        <select name="provinceId" id="provinceId" class="form-control">
                            <option value=" ">省</option>
                            <?php
                            foreach ($province as $p) {
                                if ($storehouseInfo['provinceId'] == $p['areaId']) {
                                    $selected = ' selected';
                                } else {
                                    $selected = ' ';
                                }
                                echo '<option value="' . $p['areaId'] . '" ' . $selected . '>' . $p['areaName'] . '</option>';
                            }
                            ?>
                        </select>
                    </span>
                    <span class="col-md-3 ">
                        <select name="cityId" id="cityId" class="form-control">
                            <option value=" " selected>市</option>
                            <?php
                            foreach ($city as $p) {
                                if ($storehouseInfo['cityId'] == $p['areaId']) {
                                    $selected = ' selected';
                                } else {
                                    $selected = ' ';
                                }
                                echo '<option value="' . $p['areaId'] . '" ' . $selected . '>' . $p['areaName'] . '</option>';
                            }
                            ?>
                        </select>
                    </span>
                    <span class="col-md-3 ">
                        <select name="districtId" id="districtId" class="form-control">
                            <option value=" " selected>区县</option>
                            <?php
                            foreach ($district as $p) {
                                if ($storehouseInfo['districtId'] == $p['areaId']) {
                                    $selected = ' selected';
                                } else {
                                    $selected = ' ';
                                }
                                echo '<option value="' . $p['areaId'] . '" ' . $selected . '>' . $p['areaName'] . '</option>';
                            }
                            ?>
                        </select>
                    </span>
                    <div class="showmsg">
                        <?php
                        if (isset($error['provinceId'])) {
                            $this->_view->showValidateError($error['provinceId']);
                        }
                        ?>
                        <?php
                        if (isset($error['cityId'])) {
                            $this->_view->showValidateError($error['cityId']);
                        }
                        ?>
                        <?php
                        if (isset($error['districtId'])) {
                            $this->_view->showValidateError($error['districtId']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">仓库名称 :</label>
                <div class="col-sm-10">
                    <input type="text" name="storehouseName" <?php echo $this->_view->getInputAttrs($rules, 'storehouseName') ?> id="storehouseName" value="<?php if (isset($storehouseInfo['storehouseName'])) echo $storehouseInfo['storehouseName'] ?>" class="form-control" placeholder="北京 燕郊" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['storehouseName'])) {
                            $this->_view->showValidateError($error['storehouseName']);
                        }
                        ?>
                    </div>
                </div>

            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">详细地址 :</label>
                <div class="col-sm-10">
                    <input type="text" name="address" <?php echo $this->_view->getInputAttrs($rules, 'address') ?> id="address" value="<?php if (isset($storehouseInfo['storehouseName'])) echo $storehouseInfo['address'] ?>" class="form-control" placeholder="详细地址" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['address'])) {
                            $this->_view->showValidateError($error['address']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">联系电话 :</label>
                <div class="col-sm-10">
                    <input type="text" name="tel" <?php echo $this->_view->getInputAttrs($rules, 'tel') ?> id="tel" value="<?php if (isset($storehouseInfo['storehouseName'])) echo $storehouseInfo['tel'] ?>" class="form-control" placeholder="010-88888888" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['tel'])) {
                            $this->_view->showValidateError($error['tel']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">建仓时间 :</label>
                <div class="col-sm-10">
                    <input type="text" name="openedTime" id="tel" value="<?php if (isset($storehouseInfo['openedTime'])) echo $storehouseInfo['openedTime'] ?>" class="form-control" placeholder="2014-03-01" />

                </div>
            </div>



            <div class="form-actions">
                <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
            </div>
        </form>
    </div>
</div>