<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">仓库管理</a> </li>
    <li class="active">列表</li>
</ul>


<div class="widget-list">
    <form name="jform" id="jform" action="" method="post" class="form-horizontal">
        
        
        <div class="widget-content ">

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                        <th>仓库名称</th>
                        <th>地区</th>
                        <th>详细地址</th>
                        <th>联系电话</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (is_array($data) && !empty($data)) {
                        foreach ($data as $key => $item) {
                            ?>
                            <tr>
                                <td class="checkids"><input type="checkbox" name="checkIds[]" value="<?php echo $item['storehouseId']; ?>"/></td>
                                <td><a href="/Default/Storehouse/edit/storehouseId/<?php echo $item['storehouseId']; ?>"><?php echo $item['storehouseName']; ?></a></td>
                                <td><?php echo $item['province'] . '|' . $item['city'] . '|' . $item['district']; ?></td>
                                <td><?php echo $item['address']; ?></td>
                                <td><?php echo $item['tel']; ?></td>
                            </tr>
                            <?php
                        }
                    } else {
                        ?>
                        <tr>
                            <td colspan="5">无数据！</td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5"><?php echo $pagination; ?></td>
                    </tr>

                </tfoot>
            </table>
        </div>
    </form>
</div>
