
<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">区域管理</a> </li>
    <li class="active">添加</li>
</ul>


<!--End-breadcrumbs-->
<div class="widget-box">
    <div class="widget-title">
        <h5>Area-info</h5>
    </div>
    <div class="widget-content nopadding">
        <form name="form" id="form" action="" method="post" class="form-horizontal validate">
            <div class="form-group control-group">
                <label for="parentId" class="col-sm-2 control-label">父分类：</label>
                <div class="col-sm-10">
                    <select name="parentId" id="parentId" class="form-control">
                        <option value="0" selected>顶级</option>
                        <?php echo $treeArea; ?>
                    </select>
                </div>
            </div>
            <div class="form-group control-group">
                <label for="areaName" class="col-sm-2 control-label">区域名称：</label>
                <div class="col-sm-10">
                    <input type="text" name="areaName" <?php echo $this->_view->getInputAttrs($rules, 'areaName') ?> id="areaName" value="<?php if (isset($post['areaName'])) echo $post['areaName'] ?>"  class="form-control" placeholder="北京 北京周边 燕郊" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['areaName'])) {
                            $this->_view->showValidateError($error['areaName']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label for="pinyin" class="col-sm-2 control-label">拼音：</label>
                <div class="col-sm-10">
                    <input type="text" name="pinyin" <?php echo $this->_view->getInputAttrs($rules, 'pinyin') ?> id="pinyin" value="<?php if (isset($post['areaName'])) echo $post['pinyin'] ?>" class="form-control" placeholder="beijing zhoubian yanjiao" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['pinyin'])) {
                            $this->_view->showValidateError($error['pinyin']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label for="sort" class="col-sm-2 control-label">排序：</label>
                <div class="col-sm-10">
                    <input type="text" name="sort" <?php echo $this->_view->getInputAttrs($rules, 'sort') ?> id="sort" value="<?php if (isset($post['areaName'])) echo $post['sort'] ?>" class="form-control" placeholder="数字0123..." />
                    <div class="showmsg">
                        <?php
                        if (isset($error['sort'])) {
                            $this->_view->showValidateError($error['sort']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label for="public" class="col-sm-2 control-label">是否公开：</label>
                <div class="col-sm-10">
                    <label>
                        <input type="radio" name="public" value="1" checked <?php
                        if (isset($post['public'])) {
                            if ($post['public'] == 1) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        }
                        ?>/>
                        是
                    </label>
                    <label>
                        <input type="radio" name="public" value="0" <?php
                        if (isset($post['public'])) {
                            if ($post['public'] == 0) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        }
                        ?>/>
                        否 
                    </label>
                </div>
            </div>

            <div class="form-actions">
                <label for="button" class="col-sm-2 control-label"></label>
                <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
            </div>
        </form>
    </div>
</div>
