<!-- Fixed navbar -->
<?php
    $userInfo = unserialize(base64_decode($_COOKIE['_USERINFO']));

    $realName = $userInfo['realName'];
    $groupName = $userInfo['groupName'];
?>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="javascript:void(0);"><span style="font-size: 24px;">家大.</span>小区超市</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="javascript:void(0);"><?php echo $groupName;?>：<?php echo $realName;?></a></li>
                <li><a href="javascript:void(0);">
                        <select class="input2">
                            
                            <optgroup label="后台">
                                <option value="Default" selected>默认</option>
                            </optgroup>
                            <?php
                                if($industryList){
                                    foreach ($industryList as $key => $industry) {
                                      
                            ?>
                            <optgroup label="<?php echo $industry['name'];?>">
                                <?php
                                if($industry['items']){
                                    foreach ($industry['items'] as $k => $item) {
                                      
                            ?>
                                <option value="<?php echo $item['english'];?>"><?php echo $item['industryName'];?></option>
                                <?php
                              
                                    }
                                }
                            ?>
                            </optgroup>
                            <?php
                              
                                    }
                                }
                            ?>
                        </select>
                    </a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">行业： <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="/Login/logout">退出</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>