<!DOCTYPE html>
<html>
    <head>
        <?php
        if (isset($_page['title']) && $_page['title']) {
            $title = $_page['title']; //this->_layouttitle;
        } else {
            $title = '家大.小区服务-数据后台管理系统';
        }

        $static_domain = $_config_domain['static'];
        ?>
        <title><?php echo $title;?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--全局css文件-->
        <!-- Bootstrap -->
        <link rel="stylesheet" href="//<?php echo $static_domain;?>/plugin/bootstrap303/css/bootstrap.min.css">
        <link rel="stylesheet" href="//<?php echo $static_domain;?>/plugin/jquery_treeview/jquery.treeview.css" />
        <link rel="stylesheet" href="//<?php echo $static_domain;?>/css/admin/admin.css" />
        
        <!--action page additional files-->
        <?php
            if (isset($_page['static_css_files']) && is_array($_page['static_css_files'])) {
                echo $this->_view->_css($_page['static_css_files']);
            }
        ?>
        
        <!--全局js文件-->        
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <script src="//<?php echo $static_domain;?>/js/basic/libs/jquery.min.js"></script>
        <script src="//<?php echo $static_domain;?>/plugin/bootstrap303/js/bootstrap.min.js"></script>
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
            <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--top-Header-menu-->
        <?php include_once 'layout_header.phtml'; ?>

        <!--close-top-Header-menu-->


        <div class="container">
            <div class="row" style="padding-top: 60px;">
                <div id="left" class="col-md-3">
                    <!--sidebar-menu-->
                    <?php include_once 'layout_left.phtml'; ?>

                </div>
                <div id="right" class="col-md-9 nopadding">
                    <!--main-container-part-->
                    <div class="content">
                        <!--Action boxes-->
                        <?php
                        echo $_ActionContent;
                        ?>
                        <!--End Action boxes-->
                    </div>
                </div>
            </div>


        </div>
        <!--Footer-part-->
        <?php include_once 'layout_footer.phtml'; ?>

    </body>
</html>