<!--sidebar-menu-->
<div id="sidetree" class="breadcrumb">
    <div id="sidetreecontrol"><a href="?#">Collapse All</a> | <a href="?#">Expand All</a></div>
    <ul id="tree" >                        
        <li><span>商品管理中心</span>
            <ul>
                <li><a href="/Chaoshi/Goodscate/index" class="selected">商品分类管理</a>
                    <ul>
                        <li><a href="/Chaoshi/Goodscate/add">添加分类</a></li>
                    </ul>
                </li>
                <li><a href="/Chaoshi/Goodsbrand/index">商品品牌管理</a>
                    <ul>
                        <li><a href="#">添加品牌</a></li>
                    </ul>
                </li>
                <li><a href="/Chaoshi/Goods/index">商品管理</a>
                    <ul>
                        <li><a href="/Chaoshi/Goods/add">添加商品</a></li>
                    </ul>
                </li>

            </ul>
        </li>
        <li><span>区域管理中心</span>
            <ul>
                <li><a href="/Default/Area/index">地区管理</a>
                    <ul>
                        <li><a href="/Default/Area/add">新增地区</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><span>仓库管理中心</span>
            <ul>
                <li><a href="/Default/Storehouse/index">仓库管理</a>
                    <ul>
                        <li><a href="/Default/Storehouse/add">新增仓库</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><span>权限管理中心</span>
            <ul>
                <li><a href="/Default/Agroup/index">用户组管理</a>
                    <ul>
                        <li><a href="/Default/Agroup/add">新增用户组</a></li>
                    </ul>
                </li>
                <li><a href="/Default/Admin/index">管理员管理</a>
                    <ul>
                        <li><a href="/Default/Admin/add">新增管理员</a></li>
                    </ul>
                </li>
            </ul>
        </li>

    </ul>
</div>
<!--sidebar-menu-->