<div class="w">
    <div class="breadcrumb">
        <strong><a href="http://channel.jd.com/food.html">食品饮料</a></strong>
        <span>&nbsp;&gt;&nbsp;<a href="http://channel.jd.com/1320-1585.html">饮料冲调</a>&nbsp;&gt;&nbsp;<a href="http://list.jd.com/list.html?cat=1320,1585,9434">牛奶乳品</a></span>
    </div>
</div>
<div class="w main">
    <div class="left">
        <div class="category">
<!--           
            <div class="hd">
                <h3>
                    <a href="javascript:void(0);">所有类目</a>
                </h3>
            </div>
-->
            <?php
            if (isset($catList) && $catList) {
                ?>
                <div class="m ztree" id="sortlist">

                    <?php
                    foreach ($catList as $key => $cItems) {

                        //css style
                        if (isset($catesId[1]) && $catesId[1] == $cItems['cateId']) {
                            $current = " current";
                            $cOpen = " cOpen";
                        } else {
                            $current = '';
                            $cOpen = ' cBlock';
                        }
                        ?>
                        <div class="item <?php echo $current; ?>">
                            <!--cOpen|cBlock-->
                            <h3 class="<?php echo $cOpen; ?>"><?php echo $cItems['cateName']; ?></h3>
                            <?php
                            if (isset($cItems['child']) && $cItems['child']) {
                                ?>
                                <ul>
                                    <?php
                                    foreach ($cItems['child'] as $k => $item) {
                                        if (isset($catesId[2]) && $catesId[2] == $item['cateId']) {
                                            $cur = " cur";
                                        } else {
                                            $cur = '';
                                        }

                                        if (isset($item['parentPath']) && $item['parentPath']) {
                                            $catNode = $item['parentPath'] . ',' . $item['cateId'];
                                        } else {
                                            $catNode = '';
                                        }
                                        ?>
                                        <li><a class="<?php echo $cur; ?>" href="<?php echo '/List?cat=' . $catNode; ?>" target="_self"><?php echo $item['cateName']; ?></a></li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                                <?php
                            }
                            ?>
                        </div>
                        <?php
                    }
                    ?>

                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="right-extra">
        <div id="select" class="m">
            <div class="mt">
                <h1>牛奶乳品 -<strong>&nbsp;商品筛选</strong></h1>
            </div>
            <div class="mc attrs">
                <?php
                if (isset($searchTerms) && $searchTerms) {
                    foreach ($searchTerms as $key => $sItem) {
                        if (trim($sItem['attrValues'])) {
                            $attrValues = explode("\r", $sItem['attrValues']);
                        } else {
                            $attrValues = array();
                        }
                        ?>
                        <div class="prop-attrs">
                            <div class="attr">
                                <div class="a-key"><?php echo $sItem['attrName']; ?>：</div>
                                <div class="a-values">
                                    <div class="v-fold">
                                        <ul class="f-list">
                                            <li><a href="<?php echo $this->buildUrl(array('sc' => $sItem['attrId'] . ':', 'sc_append' => true)); ?>" target="_self">不限</a></li>
        <?php
        if ($attrValues) {
            foreach ($attrValues as $av) {
                if ($av) {
                    $env = $sItem['attrId'] . ':' . $av;
                } else {
                    $env = 'javascript:void(0)';
                }
                ?>
                                                    <li><a href="<?php echo $this->buildUrl(array('sc' => $env, 'sc_append' => true)); ?>" <?php if (isset($searchCondition) && is_array($searchCondition) && in_array($env, $searchCondition)) {
                                        echo ' class="cur"';
                                    } ?> target="_self"><?php echo $av; ?></a></li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                    </div>
                                    <div option="more" class="v-option hide"><span class="o-more unfold"><b></b>更多</span></div>
                                    <div option="less" class="v-option hide"><span class="o-more unfold"><b></b>收起</span></div>
                                </div>
                            </div>
                        </div>
                        <?php
                    }
                }
                ?>

            </div>
        </div>

        <div id="filter">
            <div class="cls"></div>
            <div class="fore1"><dl class="order">
                    <dt>排序：</dt>
                    <dd <?php if (isset($sort) && is_array($sort) && $sort[0] == 'sales') {
                    echo ' class="curr"';
                } else {
                    echo '';
                } ?>><a href="<?php echo $this->buildUrl(array('sort' => 'sales_desc', 'sort_append' => false)); ?>" target="_self">销量</a><b></b></dd>
                    <?php
                    if (isset($sort) && is_array($sort) && $sort[0] == 'price') {
                        $currClass = ' class="curr"';
                        if ($sort[1] == 'asc') {
                            $sortway = 'desc';
                        } elseif ($sort[1] == 'desc') {
                            $sortway = 'asc';
                        } else {
                            $sortway = 'asc';
                        }
                    } else {
                        $currClass = '';
                        $sortway = 'asc';
                    }
                    ?>
                    <dd <?php echo $currClass; ?>><a href="<?php echo $this->buildUrl(array('sort' => 'price_' . $sortway, 'sort_append' => false)); ?>" target="_self">价格</a><b></b></dd>
                    <dd <?php if (isset($sort) && is_array($sort) && $sort[0] == 'commentcount') {
                        echo ' class="curr"';
                    } else {
                        echo '';
                    } ?>><a href="<?php echo $this->buildUrl(array('sort' => 'commentcount_desc', 'sort_append' => false)); ?>" target="_self">评论数</a><b></b></dd>
                    <dd <?php if (isset($sort) && is_array($sort) && $sort[0] == 'time') {
                        echo ' class="curr"';
                    } else {
                        echo '';
                    } ?>><a href="<?php echo $this->buildUrl(array('sort' => 'time_desc', 'sort_append' => false)); ?>" target="_self">上架时间</a><b></b></dd>
                </dl>
                <div class="pagin pagin-m">
                    <span class="text"><i><?php echo $pageNum; ?></i>/<?php echo $totalpage; ?></span>
                    <a href="<?php echo $this->buildUrl(array('p' => $prePage, 'p_append' => false)); ?>" class="prev">上一页<b></b></a>
                    <a href="<?php if ($nextPage <= 1) {
                    echo 'javascript:void(0);';
                } else {
                    echo $this->buildUrl(array('p' => $nextPage, 'p_append' => false));
                } ?>" class="next">下一页<b></b></a>
                </div>
                <div class="total"><span>共<strong><?php echo $total; ?></strong>个商品</span></div><span class="clr"></span></div>
        </div>

        <div id="plist" class="m plist-n7a ordinary-prebuy">
            <ul class="list-h">
<?php
if ($pList && is_array($pList)) {
    foreach ($pList as $k => $pItem) {
        if (isset($pItem['packPic']) && $pItem['packPic']) {
            $pics = explode(',', $pItem['packPic']);
            $firstPic = $pics[0];
            $goodsPic = $fileImg_obj->generateImgUrl(array('imgSize' => '160X160', 'imgUrl' => $firstPic), $imagesConfig);
        } else {
            $goodsPic = '';
        }
        ?>
                        <li>
                            <div class="lh-wrap">
                                <div class="p-img">
                                    <a target="_blank" href="<?php echo '/detail?p=' . $pItem['priceId']; ?>">
                                        <img width="160" height="160" alt="<?php echo $pItem['goodsName']; ?>" src="<?php echo $goodsPic; ?>" title="家大自营，安全放心！">
                                    </a>
                                </div>
                                <div class="p-name">
                                    <a target="_blank" href="<?php echo '/detail?p=' . $pItem['priceId']; ?>" title="<?php echo $pItem['goodsName']; ?>">
        <?php echo $pItem['goodsName']; ?>
                                        <font style="color: #ff0000;" name="585564" class="adwords">家大自营，安全放心！</font>
                                    </a>
                                </div>
                                <div class="p-price">
                                    <strong>￥<?php echo $pItem['currentPrice']; ?></strong>
                                    <span id="p585564"></span>
                                </div>
                                <div class="extra">
                                    <span class="evaluate"><a target="_blank" href="http://item.jd.com/585564.html#comments-list">已有33654人评价</a></span>
                                    <span class="reputation">(64%好评)</span>
                                </div>
                                <div class="stocklist"><span class="st33">北京有货</span></div>
                                <div class="btns">
                                    <a  href="javascript:void(0);" class="btn-buy">加入购物车</a>
                                </div>
                                <div class="p-shopnum"></div>

                            </div>
                        </li>
        <?php
    }
}else{
    ?>
                        <p>
                            <font style="font-size: 14px;">&nbsp;亲，没有找到符合条件的商品！<a href="javascript:history.back();" class="link_1">返回</a></font>
                        </p>
        <?php
}
?>

            </ul>
        </div>
        <div class="m clearfix">
            <div class="pagin fr">
<?php echo $pagination; ?>
            </div>
        </div>


    </div>
    <div class="clr"> </div>
</div>