<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>

        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
        <title>jQuery treeview</title>

        <link rel="stylesheet" href="/templates/tree/css/jquery.treeview.css" />
        <link rel="stylesheet" href="/templates/tree/css/screen.css" />

        <!--<script src="/templates/tree/js/jquery.js" type="text/javascript"></script>-->
        <script src="/templates/tree/js/jquery.cookie.js" type="text/javascript"></script>
        <script src="/templates/tree/js/jquery.treeview.js" type="text/javascript"></script>

        <script type="text/javascript" src="/templates/tree/js/demo.js"></script>

    </head>
    <body>
        <?php

        function treeRecursion($data) {
            $html = '<ul>';
            foreach ($data as $key => $fileName) {
                if (is_array($data[$key])) {
                    $html .= "<li >";
                    $html .= "<span>$key</span>";
                    $html .= treeRecursion($fileName);
                    $html .= "</li>";
                } else {
                    
//                    $html .= "<li  class='closed'>$fileName</li>";
                    $html .= '<li><a href="javascript:help(\'' . str_replace(DS, ':', $fileName) . '\');">' . basename($fileName) . '</a></li>';
                }
            }
            $html .= '</ul>';
            return $html;
        }
        ?>
        <div id="treecontrol">
            <a title="Collapse the entire tree below" href="#"><img src="/templates/tree/images/minus.gif" /> 展开</a>

            <a title="Expand the entire tree below" href="#"><img src="/templates/tree/images/plus.gif" /> 关闭</a>
        </div>
        <ul id="black" class="treeview-black">
            <?php
            foreach ($data as $key => $fileName) {
                if (is_array($data[$key])) {
                    echo "<li><span>$key</span>";
                    echo treeRecursion($fileName);
                    echo "</li>";
                } else {
                    echo '<li><a href="javascript:help(\'' . str_replace(DS, ':', $fileName) . '\');">' . $fileName . '</a></li>';
//                    echo "<li>$fileName</li>";
                }
                ?>

                <?php
            }
            ?>
            
        </ul>



        </div>

    </body>
</html>