<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>

        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
        <title>jQuery treeview</title>

        <link rel="stylesheet" href="/templates/tree/css/jquery.treeview.css" />
        <link rel="stylesheet" href="/templates/tree/css/screen.css" />

        <script src="/templates/tree/js/jquery.js" type="text/javascript"></script>
        <script src="/templates/tree/js/jquery.cookie.js" type="text/javascript"></script>
        <script src="/templates/tree/js/jquery.treeview.js" type="text/javascript"></script>

        <script type="text/javascript" src="/templates/tree/js/demo.js"></script>

    </head>
    <body>

        <div id="treecontrol">
            <a title="Collapse the entire tree below" href="#"><img src="/templates/tree/images/minus.gif" /> Collapse All</a>
            <a title="Expand the entire tree below" href="#"><img src="/templates/tree/images/plus.gif" /> Expand All</a>
            <a title="Toggle the tree below, opening closed branches, closing open branches" href="#">Toggle All</a>
        </div>
        <ul id="black" class="treeview-black">
            <li>Item 1</li>
            <li>
                <span>Item 2</span>
                <ul>
                    <li>
                        <span>Item 2.1</span>
                        <ul>
                            <li>Item 2.1.1</li>
                            <li>Item 2.1.2</li>
                        </ul>
                    </li>
                    <li>Item 2.2</li>
                    <li class="closed">
                        <span>Item 2.3 (closed at start)</span>
                        <ul>
                            <li>Item 2.3.1</li>
                            <li>Item 2.3.2</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
        <ul id="gray" class="treeview-gray">
            <li>Item 1</li>
            <li>
                <span>Item 2</span>
                <ul>
                    <li class="closed">
                        <span>Item 2.1 (closed at start)</span>
                        <ul>
                            <li>Item 2.1.1</li>
                            <li>Item 2.1.2</li>
                        </ul>
                    </li>
                    <li>Item 2.2.1</li>
                    <li>Item 2.2.2</li>
                    <li>Item 2.2.3</li>
                    <li>Item 2.2.4</li>
                    <li>Item 2.2.5</li>
                    <li>Item 2.2.6</li>
                    <li>Item 2.2.7</li>
                    <li>Item 2.2.8</li>
                    <li>
                        <span>Item 2.3</span>
                        <ul>
                            <li>Item 2.3.1</li>
                            <li>Item 2.3.2</li>
                            <li>Item 2.3.3</li>
                            <li>Item 2.3.4</li>
                            <li>Item 2.3.5</li>
                            <li>Item 2.3.6</li>
                            <li>Item 2.3.7</li>
                            <li>Item 2.3.8</li>
                            <li>Item 2.3.9</li>
                        </ul>
                    </li>
                    <li>
                        <span>Item 2.4</span>
                        <ul>
                            <li>Item 2.4.1</li>
                            <li>Item 2.4.2</li>
                            <li>Item 2.4.3</li>
                            <li>Item 2.4.4</li>
                            <li>Item 2.4.5</li>
                            <li>Item 2.4.6</li>
                            <li>Item 2.4.7</li>
                            <li>Item 2.4.8</li>
                            <li>Item 2.4.9</li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>Item 3</li>
        </ul>	

        </div>

    </body>
</html>