<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="/Index/index"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index/cateParentId/$gcateInfo[cateId]"; ?>">商品品牌管理</a> </li>
    <li class="active">编辑</li>
</ul>

<!--End-breadcrumbs-->
<div class="widget-box">
    <div class="widget-title">
        <h5>Goods Brand-info</h5>
    </div>
    <div class="widget-content nopadding">
        <form action="" method="post" class="form-horizontal validate">
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">分类 :</label>
                <div class="col-sm-10">

                    <input type="text" name="cateName"  value="<?php echo $gcateInfo['cateName']; ?>" class="form-control" readonly/>
                    
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">商品类型 :</label>
                <div class="col-sm-10">
                    <?php
                    foreach ($childCateType as $key => $v) {
                        ?>
                        <span><input type="checkbox" name="childCateType[]" <?php echo $this->_view->getInputAttrs($rules, 'childCateType') ?> value="<?php echo $v['cateId']; ?>" <?php if (in_array($v['cateId'], $gbrandInfo['childCateType'])) echo ' checked'; ?>/> <?php echo $v['cateName']; ?></span>
                        <?php
                    }
                    ?>
                    <div class="showmsg">
                        <?php
                        if (isset($error['childCateType'])) {
                            $this->_view->showValidateError($error['childCateType']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">商品品牌名称 :</label>
                <div class="col-sm-10">
                    <input type="text" name="brandName" <?php echo $this->_view->getInputAttrs($rules, 'brandName') ?> id="cateName" value="<?php if (isset($gbrandInfo['brandName'])) echo $gbrandInfo['brandName'] ?>" class="form-control" placeholder="三元 蒙牛 伊利" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['brandName'])) {
                            $this->_view->showValidateError($error['brandName']);
                        }
                        ?>
                    </div>
                </div>

            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">拼音 :</label>
                <div class="col-sm-10">
                    <input type="text" name="pinyin" <?php echo $this->_view->getInputAttrs($rules, 'pinyin') ?> id="pinyin" value="<?php if (isset($gbrandInfo['pinyin'])) echo $gbrandInfo['pinyin'] ?>" class="form-control" placeholder="sanyuan mengniu yili" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['pinyin'])) {
                            $this->_view->showValidateError($error['pinyin']);
                        }
                        ?>
                    </div>
                </div>
            </div>

            <div class="form-group control-group">
                <label for="status" class="col-sm-2 textRight">状态设置：</label>
                <div class="col-sm-10">
                    <label>
                        <input type="radio" name="status" value="1" checked <?php
                        if (isset($gbrandInfo['status'])) {
                            if ($gbrandInfo['status'] == 1) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        }
                        ?>/>
                        公开
                    </label>
                    <label>
                        <input type="radio" name="status" value="-1" <?php
                        if (isset($gbrandInfo['status'])) {
                            if ($gbrandInfo['status'] == -1) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        }
                        ?>/>
                        不公开 
                    </label>
                    <label>
                        <input type="radio" name="status" value="-2" <?php
                        if (isset($gbrandInfo['status'])) {
                            if ($gbrandInfo['status'] == -2) {
                                echo ' checked';
                            } else {
                                echo ' ';
                            }
                        }
                        ?>/>
                        删除 
                    </label>
                </div>
            </div>



            <div class="form-actions">
                <input type="hidden" name="brandId" id="brandId" value="<?php if (isset($gbrandInfo['brandId'])) echo $gbrandInfo['brandId'] ?>" class="form-control" placeholder="" />
                <button type="submit" class="btn btn-success">Save</button>
                <button type="reset" class="btn btn-primary">Reset</button>
            </div>
        </form>
    </div>
</div>