<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="/Index/index"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index" ?>">商品品牌管理</a> </li>
    <li class="active">列表</li>
</ul>

<div class="widget-list">

    <div class="widget-event">
        <span class="submenu pull-right"><button type="submit" name="jsubmit" value="del" class="btn btn-sm btn-info" >删除</button></span>
        <span class="submenu pull-right"><button type="submit" name="jsubmit" value="add" class="btn btn-sm btn-info" onclick="location.href = '<?php echo "/$_ModuleName/$_ControllerName/add/cateParentId/$cateParentId"; ?>';">添加品牌</button></span>
    </div>
    <div class="widget-content">
        <form name="jform" id="jform" action="" method="get" class="form-horizontal">
            <div class="search">
                <span class="col-sm-2 nopadding">
                    <select name="gcateChildren" class="form-control input-sm">
                        <?php
                            if($gcateChildren){
                                foreach($gcateChildren as $key=>$childs){
                                    if($childs['parentId'] == $cateParentId){
                                        $tag = '......&nbsp;|&nbsp;';
                                    }else{
                                        $tag='';
                                    }
                        ?>
                        <option value="<?php echo $childs['cateId'];?>" <?php
                        if ($request['gcateChildren'] == $childs['cateId']) {
                            echo ' selected';
                        }elseif($cateTypeId == $childs['cateId'] && !$request['gcateChildren']){
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>><?php echo $tag.$childs['cateName'];?></option>
                        <?php
                                }
                            }
                        ?>
                    </select>
                </span>
                <span class="col-sm-2 nopadding">
                    <select name="status" class="form-control input-sm">
                        <option value="all" <?php
                        if ($request['status'] == 'all') {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>显示所有</option>
                        <option value="1" <?php
                        if ((isset($request['status']) && $request['status'] == 1) || $request['status'] =='') {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>已上线</option>
                        <option value="-1" <?php
                        if (isset($request['status']) && $request['status'] == -1) {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>未公开</option>
                        <option value="-2" <?php
                        if (isset($request['status']) && $request['status'] == -2) {
                            echo ' selected';
                        } else {
                            echo '';
                        }
                        ?>>已删除</option>
                    </select>
                </span>

                <span>
                    <button type="submit" name="jsubmit" value="search" class="btn btn-default btn-sm" >检索</button>
                </span>

            </div>


            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
                        <th>品牌名称</th>
                        <th>拼音</th>
                        <th>所属分类</th>
                        <th>商品类型</th>
                        <th>状态</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (is_array($data) && !empty($data)) {
                        foreach ($data as $key => $item) {
                            ?>
                           <tr>
                                <td class="checkids"><input type="checkbox" name="checkIds[]" value="<?php echo $item['brandId']; ?>"/></td>
                                <td><a href="<?php echo "/$_ModuleName/goodsbrand/edit/brandId/$item[brandId]"; ?>"><?php echo $item['brandName']; ?></a></td>
                                <td><?php echo $item['pinyin']; ?></td>
                                <td><?php echo $item['cateName']; ?></td>
                                <td><?php echo $item['childCateType']; ?></td>
                                <td><?php if ($item['status'] == 1) {
                                                echo '已公开';
                                            } else {
                                                echo '未公开';
                                            } ?>
                                </td>
                            </tr>
                                <?php
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="6">无数据！</td>
                            </tr>
                            <?php
                        }
                        ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6"><?php echo $pagination; ?></td>
                    </tr>

                </tfoot>
            </table>
        </form>
    </div>

</div>
