<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index/cateId/$attrcateInfo[goodsCateId]"; ?>">商品属性分类管理</a> </li>
    <li class="active">编辑</li>
</ul>

<!--End-breadcrumbs-->
<div class="widget-box">
    <div class="widget-title">
        <h5>Goods Attribute Category-info</h5>
    </div>
    <div class="widget-content nopadding">
        <form action="" method="post" class="form-horizontal validate">
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">商品分类 :</label>
                <div class="col-sm-10">
                    <input type="text" name="cateName" id="cateName" value="<?php echo $gcateInfo['cateName'] ?>" class="form-control"  readonly />
                    <input type="hidden" name="goodsCateId" <?php echo $this->_view->getInputAttrs($rules, 'goodsCateId') ?> id="cateId" value="<?php echo $gcateInfo['cateId'] ?>" class="form-control"   readonly/>
                    <div class="showmsg">
                        <?php
                        if (isset($error['goodsCateId'])) {
                            $this->_view->showValidateError($error['goodsCateId']);
                        }
                        ?>
                    </div>
                </div>

            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">属性分类名称 :</label>
                <div class="col-sm-10">
                    <input type="text" name="attrCateName" <?php echo $this->_view->getInputAttrs($rules, 'attrCateName') ?> id="attrCateName" value="<?php echo $attrcateInfo['attrCateName']; ?>" class="form-control" placeholder="基本属性" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['attrCateName'])) {
                            $this->_view->showValidateError($error['attrCateName']);
                        }
                        ?>
                    </div>
                </div>

            </div>
            <div class="form-group control-group">
                <label class="col-sm-2 control-label">排序 :</label>
                <div class="col-sm-10">
                    <input type="text" name="sort" <?php echo $this->_view->getInputAttrs($rules, 'sort') ?> id="sort" value="<?php echo $attrcateInfo['sort']; ?>" class="form-control" placeholder="0 1 2 3" />
                    <div class="showmsg">
                        <?php
                        if (isset($error['sort'])) {
                            $this->_view->showValidateError($error['sort']);
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <label for="button" class="col-sm-2 control-label"></label>
                <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
            </div>
        </form>

    </div>
</div>