
<!--Footer-part-->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="//static.jiada.local/plugin/bootstrap303/js/bootstrap.min.js"></script>
<script src="//static.jiada.local/plugin/jquery_treeview/lib/jquery.cookie.js" type="text/javascript"></script>
<script src="//static.jiada.local/plugin/jquery_treeview/jquery.treeview.js" type="text/javascript"></script>
<script src="//static.jiada.local/admin/js/jquery.validate.js" charset="utf-8"></script>
<script src="//static.jiada.local/admin/js/form.js" charset="utf-8"></script>
<script src="//static.jiada.local/admin/js/ajax.js" charset="utf-8"></script>
<script type="text/javascript">
    $(function() {
        $("#tree").treeview({
            collapsed: false,
            animated: "medium",
            control: "#sidetreecontrol",
            persist: "location"
        });
    })
$(document).ready(function() {
    var form = $('form.validate');
    if (form.length) {
        form.each(function() {
            //弹层显示错误
            autoValidate(this);
        });
    }
//    页面内显示错误
//        $("#form").validate({
//            debug: true,
//            errorElement: "div",
//            errorPlacement: function(error, element) {
//                $(".showmsg").html(error);
//            }
//        });

});
</script>