<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index"; ?>">商品管理</a> </li>
    <li class="active">添加</li>
</ul>
<!--End-breadcrumbs-->
<div class="widget-tabs-box">
    <form action="" name="jform" id="jform" method="post" class="form-horizontal validate">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">基本信息</a></li>
            <li><a  href="javascript:void();">包装图片</a></li>
            <li><a  href="javascript:void();">商品详情</a></li>
            <li><a  href="javascript:void();">商品属性</a></li>
        </ul>
        <div class="widget-content nopadding tab-content">
            <div id="tab1" class="tab-pane active">

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品分类 :</label>
                    <div class="col-sm-10">
                        <span class="col-sm-2 nopadding">
                        <select name="cateId" id="nodeCate1" class="form-control input-sm linkage" data-next="#nodeCate2" data-url="<?php echo "/$_ModuleName/Goodscate/nodeGcate/cateId";?>">
                            <option value="" selected>--选择分类--</option>
                            <?php
                            if(isset($nodeCate1)){
                                foreach ($nodeCate1 as $cate) {
                                    if (in_array($cate['id'], $post_select_cateId)) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $cate['id'] . '" ' . $selected . '>' . $cate['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </span>
                    <span class="col-sm-2 nopadding">
                        <select name="cateId" id="nodeCate2" class="form-control input-sm linkage" data-next="#nodeCate3" data-url="<?php echo "/$_ModuleName/Goodscate/nodeGcate/cateId";?>" data-display="1">
                            <option value="" selected>--选择分类--</option>
                            <?php
                            if(isset($nodeCate2)){
                                foreach ($nodeCate2 as $cate) {
                                    if (in_array($cate['id'], $post_select_cateId)) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $cate['id'] . '" ' . $selected . '>' . $cate['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </span>
                    <span class="col-sm-2 nopadding">
                        <select name="cateId" id="nodeCate3" <?php echo $this->_view->getInputAttrs($rules, 'cateId') ?> class="form-control input-sm linkage" data-next="#catebrands" data-url="<?php echo "/$_ModuleName/Goodsbrand/gcatebrand/cateId";?>" data-display="1">
                            <option value="" selected>--选择分类--</option>
                            <?php
                            if(isset($nodeCate3)){
                                foreach ($nodeCate3 as $cate) {
                                    if (in_array($cate['id'], $post_select_cateId)) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $cate['id'] . '" ' . $selected . '>' . $cate['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </span>
                        <div class="showmsg">
                            <?php
                            if (isset($error['cateId'])) {
                                $this->_view->showValidateError($error['cateId']);
                            }
                            ?>
                        </div>

                    </div>
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品品牌 :</label>
                    <div class="col-sm-10">
                        <select name="brandId" id="catebrands" <?php echo $this->_view->getInputAttrs($rules, 'brandId') ?> class="form-control input-sm linkage" data-next="" data-url="" data-display="1">
                            <option value="" selected>--选择品牌--</option>
                            <?php
                            if(isset($catebrands)){
                                foreach ($catebrands as $brand) {
                                    if ($brand['id']==$post['brandId']) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = ' ';
                                    }
                                    echo '<option value="' . $brand['id'] . '" ' . $selected . '>' . $brand['name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                        <div class="showmsg">
                            <?php
                            if (isset($error['brandId'])) {
                                $this->_view->showValidateError($error['brandId']);
                            }
                            ?>
                        </div>

                    </div>
                </div>

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品名称 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="goodsName" <?php echo $this->_view->getInputAttrs($rules, 'goodsName') ?> id="goodsName" value="<?php if (isset($post['goodsName'])) {
                                echo $post['goodsName'];
                            } ?>" class="input-sm form-control" placeholder="" />
                        <div class="showmsg">
<?php
if (isset($error['goodsName'])) {
    $this->_view->showValidateError($error['goodsName']);
}
?>
                        </div>
                    </div>

                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> 商品价格 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="originalPrice" id="originalPrice" value="<?php if (isset($post['originalPrice'])) {
                                echo $post['originalPrice'];
                            } ?>" class="input-sm form-control input2" placeholder="原价:本店售价" disabled/>
                        <input type="text" name="discount" id="discount" value="<?php if (isset($post['discount'])) {
                                echo $post['discount'];
                            } ?>" class="input-sm form-control input2" placeholder="折扣比例:0.85" disabled/>
                        <input type="text" name="currentPrice" id="currentPrice" value="<?php if (isset($post['currentPrice'])) {
                                echo $post['currentPrice'];
                            } ?>" class="input-sm form-control input2" placeholder="现价:活动促销价格" disabled/>

                    </div>                            
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label">市场价格 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="marketPrice" id="marketPrice" value="" class="input-sm form-control input2" placeholder="" />

                    </div>                            
                </div>

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label">活动促销 :</label>
                    <div class="col-md-10">
                        <input type="text" name="activityStartTime" id="activityStartTime" value="" class="input-sm form-control input2" placeholder="开始时间" disabled/>

                        <input type="text" name="activityEndTime" id="activityEndTime" value="" class="input-sm form-control input2" placeholder="结束时间" disabled/>
                    </div>
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label">推荐标签 :</label>
                    <div class="col-sm-10">
                        <select name="recTags" class="input-sm form-control">
                            <option value="0" selected>无</option>
                            <option value="1" >活动</option>
                            <option value="2" >热销</option>
                            <option value="3" >新品</option>
                            <option value="4" >精品</option>
                            <option value="5" >人气</option>                                        
                        </select>
                    </div>
                </div>

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 上架 :</label>
                    <div class="col-sm-10">
                        <label>
                            <input type="radio" name="onLine" value="1" checked <?php
                            if (isset($post['onLine'])) {
                                if ($post['onLine'] == 1) {
                                    echo ' checked';
                                } else {
                                    echo ' ';
                                }
                            }
                            ?>/>
                            是
                        </label>
                        <label>
                            <input type="radio" name="onLine" value="0" <?php
                                   if (isset($post['onLine'])) {
                                       if ($post['onLine'] == 0) {
                                           echo ' checked';
                                       } else {
                                           echo ' ';
                                       }
                                   }
                            ?>/>
                            否
                        </label>
                    </div>
                </div>



                <div class="form-actions">
                    <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存，下一步</button>
                    <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
                </div>

            </div>
            <div id="tab2" class="tab-pane">
                ...

            </div>
            <div id="tab3" class="tab-pane">
                ...

            </div>

        </div>
    </form>
</div>