<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="javascript:void(0);"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index"; ?>">商品管理</a> </li>
    <li class="active">编辑</li>
</ul>

<!--End-breadcrumbs-->
<div class="widget-tabs-box">
    <form action="" name="jform" id="jform" method="post" class="form-horizontal validate">
        <ul class="nav nav-tabs">
                <li  class="active"><a href="<?php echo "/$_ModuleName/Goods/edit/goodsId/$goodsInfo[goodsId]"; ?>">基本信息</a></li>
                <li><a href="<?php echo "/$_ModuleName/Goods/packpic/goodsId/$goodsInfo[goodsId]"; ?>">包装图片</a></li>
                <li><a href="<?php echo "/$_ModuleName/Goods/detail/goodsId/$goodsInfo[goodsId]"; ?>">商品详情</a></li>
                <li><a href="<?php echo "/$_ModuleName/Goods/attr/goodsId/$goodsInfo[goodsId]"; ?>">商品属性</a></li>
            </ul>
        <div class="widget-content nopadding tab-content">
            <div id="tab1" class="tab-pane active">

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品分类 :</label>
                    <div class="col-sm-10">
                        <select name="cateId" id="cateId" <?php echo $this->_view->getInputAttrs($rules, 'cateId') ?> class="input-sm form-control">
                            <option value='' selected>--选择分类--</option>
                            <?php echo $treeGcate; ?>
                        </select>
                        <div class="showmsg">
                            <?php
                            if (isset($error['cateId'])) {
                                $this->_view->showValidateError($error['cateId']);
                            }
                            ?>
                        </div>

                    </div>
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品品牌 :</label>
                    <div class="col-sm-10">
                        <select name="brandId" id="brandId" <?php echo $this->_view->getInputAttrs($rules, 'brandId') ?> class="input-sm form-control">                                        
                            <option value='' selected>--选择品牌--</option>
                            <?php
                            if (isset($brands) && $brands) {
                                foreach ($brands as $key => $val) {
                                    if ($brandId == $val['brandId']) {
                                        $selected = ' selected';
                                    } else {
                                        $selected = '';
                                    }
                                    echo "<option value='" . $val[brandId] . "' $selected>" . $val['brandName'] . "</option>";
                                }
                            }
                            ?>
                        </select>
                        <div class="showmsg">
                            <?php
                            if (isset($error['brandId'])) {
                                $this->_view->showValidateError($error['brandId']);
                            }
                            ?>
                        </div>

                    </div>
                </div>

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品名称 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="goodsName" <?php echo $this->_view->getInputAttrs($rules, 'goodsName') ?> id="brandName" value="<?php if (isset($goodsInfo['goodsName'])) {
                                echo $goodsInfo['goodsName'];
                            } ?>" class="input-sm form-control" placeholder="" />
                        <div class="showmsg">
                        <?php
                        if (isset($error['goodsName'])) {
                            $this->_view->showValidateError($error['goodsName']);
                        }
                        ?>
                        </div>
                    </div>

                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> 商品价格 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="originalPrice" id="originalPrice" value="<?php if (isset($goodsInfo['originalPrice'])) {
                                echo $goodsInfo['originalPrice'];
                            } ?>" class="input-sm form-control input2" placeholder="原价:本店售价" disabled/>
                        <input type="text" name="discount" id="discount" value="<?php if (isset($goodsInfo['discount'])) {
                                echo $goodsInfo['discount'];
                            } ?>" class="input-sm form-control input2" placeholder="折扣比例:0.85" disabled/>
                        <input type="text" name="currentPrice" id="currentPrice" value="<?php if (isset($goodsInfo['currentPrice'])) {
                                echo $goodsInfo['currentPrice'];
                            } ?>" class="input-sm form-control input2" placeholder="现价:活动促销价格" disabled/>
                        
                    </div>                            
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label">市场价格 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="marketPrice" id="marketPrice" value="<?php if (isset($goodsInfo['marketPrice'])) {
                                echo $goodsInfo['marketPrice'];
                            } ?>" class="input-sm form-control input2" placeholder="" />
                        
                        </div>
                    </div>                            
                </div>

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label">活动促销 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="activityStartTime" id="activityStartTime" value="<?php if (isset($goodsInfo['activityStartTime'])) {
                                echo $goodsInfo['activityStartTime'];
                            } ?>" class="input-sm form-control input2" placeholder="开始时间" disabled/>
                        <input type="text" name="activityEndTime" id="activityEndTime" value="<?php if (isset($goodsInfo['activityEndTime'])) {
                                echo $goodsInfo['activityEndTime'];
                            } ?>" class="input-sm form-control input2" placeholder="结束时间" disabled/>

                    </div>                            
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label">推荐标签 :</label>
                    <div class="col-sm-10">
                        <select name="recTags" class="input-sm form-control">
                            <?php
                            $reTagsArr = array('1' => 活动, '2' => 热销, '3' => 新品, '4' => 精品, '5' => 人气);
                            ?>
                            <option value="0" selected>无</option>
                            <?php
                            foreach ($reTagsArr as $key => $value) {
                                $goodsInfo['recTags'] == $key ? $selected = ' selected' : $selected = ' ';
                                ?>
                                <option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
                                <?php
                                   }
                                   ?>                                   
                        </select>
                    </div>
                </div>

                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 上架 :</label>
                    <div class="col-sm-10">
                        <label>
                            <input type="radio" name="onLine" value="1" checked <?php
                            if (isset($goodsInfo['onLine'])) {
                                if ($goodsInfo['onLine'] == 1) {
                                    echo ' checked';
                                } else {
                                    echo ' ';
                                }
                            }
                            ?>/>
                            是
                        </label>
                        <label>
                            <input type="radio" name="onLine" value="0" <?php
                            if (isset($goodsInfo['onLine'])) {
                                if ($goodsInfo['onLine'] == 0) {
                                    echo ' checked';
                                } else {
                                    echo ' ';
                                }
                            }
                            ?>/>
                            否
                        </label>
                    </div>
                </div>



                <div class="form-actions">
                    <button type="submit" name="jsubmit" value="save" class="btn btn-success">保存</button>
                    <button type="reset" name="jsubmit" value="reset" class="btn btn-primary">重置</button>
                </div>

            </div>
            <div id="tab2" class="tab-pane">
                ......
            </div>
            <div id="tab3" class="tab-pane">
                ......

            </div>

        </div>
    </form>
</div>