<!--breadcrumbs-->
<ul class="breadcrumb" contenteditable="false">
    <li><a href="/Index/index"  title="Go to Home">主页</a> </li>
    <li><a href="<?php echo "/$_ModuleName/$_ControllerName/index/cateId/$goodsCateId"; ?>">商品属性管理</a> </li>
    <li class="active">添加</li>
</ul>


<!--End-breadcrumbs-->
<div class="widget-tabs-box">
    <ul class="nav nav-tabs">
        <li><a href="<?php echo "/$_ModuleName/goodsattrcate/index/cateId/$goodsCateId"; ?>">商品属性分类管理</a></li>
        <li class="active"><a href="<?php echo "/$_ModuleName/goodsattr/index/cateId/$goodsCateId"; ?>">商品属性管理</a></li>
    </ul>
    <div class="widget-content nopadding tab-content">
        <div id="tab1" class="tab-pane">

        </div>
        <div id="tab2" class="tab-pane active">
            <p></p>
            <form action="" name="jform" id="jform" method="post" class="form-horizontal validate">
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 商品分类 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="cateName" id="cateName" value="<?php echo $gcateInfo['cateName'] ?>" class="form-control input-sm"  readonly />
                        <input type="hidden" name="goodsCateId" <?php echo $this->_view->getInputAttrs($rules, 'goodsCateId') ?> id="cateId" value="<?php echo $gcateInfo['cateId'] ?>" class="form-control input-sm" readonly/>
                        <div class="showmsg">
                            <?php
                            if (isset($error['goodsCateId'])) {
                                $this->_view->showValidateError($error['goodsCateId']);
                            }
                            ?>
                        </div>
                    </div>

                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 属性分类 :</label>
                    <div class="col-sm-10">
                        <select name="attrCateId" class="form-control input-sm">
                            <?php
                            foreach ($goodsAttrCate as $k => $v) {
                                ?>
                                <option value="<?php echo $v['attrCateId']; ?>" ><?php echo $v['attrCateName']; ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 属性名称 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="attrName" <?php echo $this->_view->getInputAttrs($rules, 'attrName') ?> id="attrCateName" value="" class="form-control input-sm" placeholder="如：作者 出版日期" />
                        <div class="showmsg">
                            <?php
                            if (isset($error['attrName'])) {
                                $this->_view->showValidateError($error['attrName']);
                            }
                            ?>
                        </div>
                    </div>

                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 属性值录入方式 :</label>
                    <div class="col-sm-10">
                        <select name="attrInputType" class="form-control input-sm">
                            <option value="text" selected>文本【text】</option>
                            <option value="select" >下拉框【select】</option>
                            <option value="checkbox" >复选【checkbox】</option>
                            <option value="radio" >单选【radio】</option>
                            <option value="textarea" >大文本【textarea】</option>                                        
                        </select>
                    </div>
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label">可选值列表 :</label>
                    <div class="col-sm-10">
                        <textarea name="attrValues" placeholder="多个值敲回车分隔；如果录入方式是：select checkbox radio，此项必填！" class="form-control input-sm" rows="6"></textarea>                                    
                        <div class="showmsg">
                            <?php
                            if (isset($error['attrValues'])) {
                                $this->_view->showValidateError($error['attrValues']);
                            }
                            ?>
                        </div>
                    </div>

                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 textRight">是否必填项 :</label>
                    <div class="col-sm-10">
                        <label>
                            <input type="radio" name="isRequired" value="1" <?php if (isset($post['isRequired'])) {
                                if ($post['isRequired'] == 1) {
                                    echo ' checked';
                                } else {
                                    echo ' ';
                                }
                            } ?>/>
                            是
                        </label>
                        <label>
                            <input type="radio" name="isRequired" value="0" checked <?php if (isset($post['isRequired'])) {
                                if ($post['isRequired'] == 0) {
                                    echo ' checked';
                                } else {
                                    echo ' ';
                                }
                            } ?>/>
                            否 
                        </label>
                    </div>
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 textRight">检索项 :</label>
                    <div class="col-sm-10">
                        <label>
                            <input type="radio" name="searchTerms" value="1" <?php if (isset($post['searchTerms'])) {
                                if ($post['searchTerms'] == 1) {
                                    echo ' checked';
                                } else {
                                    echo ' ';
                                }
                            } ?>/>
                            是
                        </label>
                        <label>
                            <input type="radio" name="searchTerms" value="0" checked <?php if (isset($post['searchTerms'])) {
                                if ($post['searchTerms'] == 0) {
                                    echo ' checked';
                                } else {
                                    echo ' ';
                                }
                            } ?>/>
                            否 
                        </label>
                    </div>
                </div>
                <div class="form-group control-group">
                    <label class="col-sm-2 control-label"> <b class="bold red">*</b> 排序 :</label>
                    <div class="col-sm-10">
                        <input type="text" name="sort" <?php echo $this->_view->getInputAttrs($rules, 'sort') ?> id="sort" value="0" class="form-control input-sm" placeholder="01 02 03" />
                        <div class="showmsg">
                        <?php
                        if (isset($error['sort'])) {
                            $this->_view->showValidateError($error['sort']);
                        }
                        ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">Save</button>
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </form>
        </div>

    </div>
</div>